# Copyright (C) Microsoft Corporation. All rights reserved.

# Go here for details on compile.yml syntax:
# https://dev.azure.com/ms-tsd/Ether/_git/sim-tools?path=%2FSourceFileSpec.docx&version=GBmaster

---
provides: [skencode]
schema_version: 2.4.0
requires:
  - abr_defines
  - skdecode_pkg
  - abr_libs
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/skencode.sv
      
    tops: [skencode]
  rtl_lint:
    directories: []
    waiver_files:
      - $MSFT_REPO_ROOT/src/sk_decode/config/design_lint/skencode/sglint_waivers
---
provides: [skencode_tb]
schema_version: 2.4.0
requires:
  - skencode
  - skdecode_pkg
targets:
  rtl:
    directories: [$COMPILE_ROOT/tb]
    files:
      - $COMPILE_ROOT/tb/skencode_tb.sv
    tops: [skencode_tb]
  sim:
    pre_exec: 'echo "[PRE-EXEC] Copying s1 bytes hex to $PWD" && cp $COMPILE_ROOT/tb/pack_eta.py .'
