// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package adams_bridge_reg_pkg;

    localparam ADAMS_BRIDGE_REG_DATA_WIDTH = 32;
    localparam ADAMS_BRIDGE_REG_MIN_ADDR_WIDTH = 15;

    typedef struct packed{
        logic [31:0] next;
    } adams_bridge_reg__ADAMS_BRIDGE_NAME__NAME__in_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_NAME__NAME__in_t NAME;
    } adams_bridge_reg__ADAMS_BRIDGE_NAME__in_t;

    typedef struct packed{
        logic [31:0] next;
    } adams_bridge_reg__ADAMS_BRIDGE_VERSION__VERSION__in_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_VERSION__VERSION__in_t VERSION;
    } adams_bridge_reg__ADAMS_BRIDGE_VERSION__in_t;

    typedef struct packed{
        logic hwclr;
    } adams_bridge_reg__ADAMS_BRIDGE_CTRL__CTRL__in_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_CTRL__CTRL__in_t CTRL;
    } adams_bridge_reg__ADAMS_BRIDGE_CTRL__in_t;

    typedef struct packed{
        logic next;
    } adams_bridge_reg__ADAMS_BRIDGE_STATUS__READY__in_t;

    typedef struct packed{
        logic next;
    } adams_bridge_reg__ADAMS_BRIDGE_STATUS__VALID__in_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_STATUS__READY__in_t READY;
        adams_bridge_reg__ADAMS_BRIDGE_STATUS__VALID__in_t VALID;
    } adams_bridge_reg__ADAMS_BRIDGE_STATUS__in_t;

    typedef struct packed{
        logic hwclr;
    } adams_bridge_reg__ADAMS_BRIDGE_IV__IV__in_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_IV__IV__in_t IV;
    } adams_bridge_reg__ADAMS_BRIDGE_IV__in_t;

    typedef struct packed{
        logic [31:0] next;
        logic we;
        logic hwclr;
    } adams_bridge_reg__ADAMS_BRIDGE_SEED__SEED__in_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_SEED__SEED__in_t SEED;
    } adams_bridge_reg__ADAMS_BRIDGE_SEED__in_t;

    typedef struct packed{
        logic hwclr;
    } adams_bridge_reg__ADAMS_BRIDGE_SIGN_RND__SIGN_RND__in_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_SIGN_RND__SIGN_RND__in_t SIGN_RND;
    } adams_bridge_reg__ADAMS_BRIDGE_SIGN_RND__in_t;

    typedef struct packed{
        logic [31:0] next;
        logic we;
        logic hwclr;
    } adams_bridge_reg__ADAMS_BRIDGE_MSG__MSG__in_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_MSG__MSG__in_t MSG;
    } adams_bridge_reg__ADAMS_BRIDGE_MSG__in_t;

    typedef struct packed{
        logic [31:0] next;
        logic we;
        logic hwclr;
    } adams_bridge_reg__ADAMS_BRIDGE_VERIFY_RES__VERIFY_RES__in_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_VERIFY_RES__VERIFY_RES__in_t VERIFY_RES;
    } adams_bridge_reg__ADAMS_BRIDGE_VERIFY_RES__in_t;

    typedef struct packed{
        logic [31:0] next;
        logic we;
        logic hwclr;
    } adams_bridge_reg__ADAMS_BRIDGE_PRIVKEY_OUT__PRIVKEY_OUT__in_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_PRIVKEY_OUT__PRIVKEY_OUT__in_t PRIVKEY_OUT;
    } adams_bridge_reg__ADAMS_BRIDGE_PRIVKEY_OUT__in_t;

    typedef struct packed{
        logic [31:0] next;
        logic we;
        logic hwclr;
    } adams_bridge_reg__ADAMS_BRIDGE_PRIVKEY_IN__PRIVKEY_IN__in_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_PRIVKEY_IN__PRIVKEY_IN__in_t PRIVKEY_IN;
    } adams_bridge_reg__ADAMS_BRIDGE_PRIVKEY_IN__in_t;

    typedef struct packed{
        logic [31:0] next;
        logic we;
        logic hwclr;
    } adams_bridge_reg__ADAMS_BRIDGE_PUBKEY__PUBKEY__in_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_PUBKEY__PUBKEY__in_t PUBKEY;
    } adams_bridge_reg__ADAMS_BRIDGE_PUBKEY__in_t;

    typedef struct packed{
        logic [31:0] next;
        logic we;
        logic hwclr;
    } adams_bridge_reg__ADAMS_BRIDGE_SIGNATURE__SIGNATURE__in_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_SIGNATURE__SIGNATURE__in_t SIGNATURE;
    } adams_bridge_reg__ADAMS_BRIDGE_SIGNATURE__in_t;

    typedef struct packed{
        logic hwset;
    } adams_bridge_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__error_internal_sts_enable_d33001bb_next_52b75ffa_resetsignal_0d7eaa27__in_t;

    typedef struct packed{
        adams_bridge_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__error_internal_sts_enable_d33001bb_next_52b75ffa_resetsignal_0d7eaa27__in_t error_internal_sts;
    } adams_bridge_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__in_t;

    typedef struct packed{
        logic hwset;
    } adams_bridge_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__notif_cmd_done_sts_enable_dabe0b8b_next_540fa3b7__in_t;

    typedef struct packed{
        adams_bridge_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__notif_cmd_done_sts_enable_dabe0b8b_next_540fa3b7__in_t notif_cmd_done_sts;
    } adams_bridge_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__in_t;

    typedef struct packed{
        adams_bridge_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__in_t error_internal_intr_r;
        adams_bridge_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__in_t notif_internal_intr_r;
    } adams_bridge_reg__intr_block_t__in_t;

    typedef struct packed{
        logic reset_b;
        logic hard_reset_b;
        logic adams_bridge_ready;
        adams_bridge_reg__ADAMS_BRIDGE_NAME__in_t [2-1:0]ADAMS_BRIDGE_NAME;
        adams_bridge_reg__ADAMS_BRIDGE_VERSION__in_t [2-1:0]ADAMS_BRIDGE_VERSION;
        adams_bridge_reg__ADAMS_BRIDGE_CTRL__in_t ADAMS_BRIDGE_CTRL;
        adams_bridge_reg__ADAMS_BRIDGE_STATUS__in_t ADAMS_BRIDGE_STATUS;
        adams_bridge_reg__ADAMS_BRIDGE_IV__in_t [16-1:0]ADAMS_BRIDGE_IV;
        adams_bridge_reg__ADAMS_BRIDGE_SEED__in_t [8-1:0]ADAMS_BRIDGE_SEED;
        adams_bridge_reg__ADAMS_BRIDGE_SIGN_RND__in_t [8-1:0]ADAMS_BRIDGE_SIGN_RND;
        adams_bridge_reg__ADAMS_BRIDGE_MSG__in_t [16-1:0]ADAMS_BRIDGE_MSG;
        adams_bridge_reg__ADAMS_BRIDGE_VERIFY_RES__in_t [16-1:0]ADAMS_BRIDGE_VERIFY_RES;
        adams_bridge_reg__ADAMS_BRIDGE_PRIVKEY_OUT__in_t [1216-1:0]ADAMS_BRIDGE_PRIVKEY_OUT;
        adams_bridge_reg__ADAMS_BRIDGE_PRIVKEY_IN__in_t [1216-1:0]ADAMS_BRIDGE_PRIVKEY_IN;
        adams_bridge_reg__ADAMS_BRIDGE_PUBKEY__in_t [648-1:0]ADAMS_BRIDGE_PUBKEY;
        adams_bridge_reg__ADAMS_BRIDGE_SIGNATURE__in_t [1149-1:0]ADAMS_BRIDGE_SIGNATURE;
        adams_bridge_reg__intr_block_t__in_t intr_block_rf;
    } adams_bridge_reg__in_t;

    typedef struct packed{
        logic [1:0] value;
    } adams_bridge_reg__ADAMS_BRIDGE_CTRL__CTRL__out_t;

    typedef struct packed{
        logic value;
    } adams_bridge_reg__ADAMS_BRIDGE_CTRL__ZEROIZE__out_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_CTRL__CTRL__out_t CTRL;
        adams_bridge_reg__ADAMS_BRIDGE_CTRL__ZEROIZE__out_t ZEROIZE;
    } adams_bridge_reg__ADAMS_BRIDGE_CTRL__out_t;

    typedef struct packed{
        logic [31:0] value;
    } adams_bridge_reg__ADAMS_BRIDGE_IV__IV__out_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_IV__IV__out_t IV;
    } adams_bridge_reg__ADAMS_BRIDGE_IV__out_t;

    typedef struct packed{
        logic [31:0] value;
    } adams_bridge_reg__ADAMS_BRIDGE_SEED__SEED__out_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_SEED__SEED__out_t SEED;
    } adams_bridge_reg__ADAMS_BRIDGE_SEED__out_t;

    typedef struct packed{
        logic [31:0] value;
    } adams_bridge_reg__ADAMS_BRIDGE_SIGN_RND__SIGN_RND__out_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_SIGN_RND__SIGN_RND__out_t SIGN_RND;
    } adams_bridge_reg__ADAMS_BRIDGE_SIGN_RND__out_t;

    typedef struct packed{
        logic [31:0] value;
    } adams_bridge_reg__ADAMS_BRIDGE_MSG__MSG__out_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_MSG__MSG__out_t MSG;
    } adams_bridge_reg__ADAMS_BRIDGE_MSG__out_t;

    typedef struct packed{
        logic [31:0] value;
    } adams_bridge_reg__ADAMS_BRIDGE_VERIFY_RES__VERIFY_RES__out_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_VERIFY_RES__VERIFY_RES__out_t VERIFY_RES;
    } adams_bridge_reg__ADAMS_BRIDGE_VERIFY_RES__out_t;

    typedef struct packed{
        logic [31:0] value;
    } adams_bridge_reg__ADAMS_BRIDGE_PRIVKEY_IN__PRIVKEY_IN__out_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_PRIVKEY_IN__PRIVKEY_IN__out_t PRIVKEY_IN;
    } adams_bridge_reg__ADAMS_BRIDGE_PRIVKEY_IN__out_t;

    typedef struct packed{
        logic [31:0] value;
    } adams_bridge_reg__ADAMS_BRIDGE_PUBKEY__PUBKEY__out_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_PUBKEY__PUBKEY__out_t PUBKEY;
    } adams_bridge_reg__ADAMS_BRIDGE_PUBKEY__out_t;

    typedef struct packed{
        logic [31:0] value;
    } adams_bridge_reg__ADAMS_BRIDGE_SIGNATURE__SIGNATURE__out_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_SIGNATURE__SIGNATURE__out_t SIGNATURE;
    } adams_bridge_reg__ADAMS_BRIDGE_SIGNATURE__out_t;

    typedef struct packed{
        logic intr;
    } adams_bridge_reg__intr_block_t__global_intr_t_agg_sts_dd3dcf0a__out_t;

    typedef struct packed{
        logic intr;
    } adams_bridge_reg__intr_block_t__global_intr_t_agg_sts_e6399b4a__out_t;

    typedef struct packed{
        logic intr;
    } adams_bridge_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__out_t;

    typedef struct packed{
        logic intr;
    } adams_bridge_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__out_t;

    typedef struct packed{
        adams_bridge_reg__intr_block_t__global_intr_t_agg_sts_dd3dcf0a__out_t error_global_intr_r;
        adams_bridge_reg__intr_block_t__global_intr_t_agg_sts_e6399b4a__out_t notif_global_intr_r;
        adams_bridge_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__out_t error_internal_intr_r;
        adams_bridge_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__out_t notif_internal_intr_r;
    } adams_bridge_reg__intr_block_t__out_t;

    typedef struct packed{
        adams_bridge_reg__ADAMS_BRIDGE_CTRL__out_t ADAMS_BRIDGE_CTRL;
        adams_bridge_reg__ADAMS_BRIDGE_IV__out_t [16-1:0]ADAMS_BRIDGE_IV;
        adams_bridge_reg__ADAMS_BRIDGE_SEED__out_t [8-1:0]ADAMS_BRIDGE_SEED;
        adams_bridge_reg__ADAMS_BRIDGE_SIGN_RND__out_t [8-1:0]ADAMS_BRIDGE_SIGN_RND;
        adams_bridge_reg__ADAMS_BRIDGE_MSG__out_t [16-1:0]ADAMS_BRIDGE_MSG;
        adams_bridge_reg__ADAMS_BRIDGE_VERIFY_RES__out_t [16-1:0]ADAMS_BRIDGE_VERIFY_RES;
        adams_bridge_reg__ADAMS_BRIDGE_PRIVKEY_IN__out_t [1216-1:0]ADAMS_BRIDGE_PRIVKEY_IN;
        adams_bridge_reg__ADAMS_BRIDGE_PUBKEY__out_t [648-1:0]ADAMS_BRIDGE_PUBKEY;
        adams_bridge_reg__ADAMS_BRIDGE_SIGNATURE__out_t [1149-1:0]ADAMS_BRIDGE_SIGNATURE;
        adams_bridge_reg__intr_block_t__out_t intr_block_rf;
    } adams_bridge_reg__out_t;
endpackage

    localparam ADAMS_BRIDGE_REG_ADDR_WIDTH = 32'd15;

endpackage