# Copyright (C) Microsoft Corporation. All rights reserved.

# Go here for details on compile.yml syntax:
# https://dev.azure.com/ms-tsd/Ether/_git/sim-tools?path=%2FSourceFileSpec.docx&version=GBmaster

---
provides: [sigencode_z_pkg]
schema_version: 2.4.0
requires: []
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/sigencode_z_defines_pkg.sv
---
provides: [sigencode_z]
schema_version: 2.4.0
requires:
  - ntt_pkg
  - sigencode_z_pkg
  - abr_libs
  - ntt_top
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/sigencode_z_top.sv
      - $COMPILE_ROOT/rtl/sigencode_z_unit.sv
      - $COMPILE_ROOT/rtl/sigencode_z_defines_pkg.sv
      
    tops: [sigencode_z_top]
  rtl_lint:
    directories: []
    waiver_files:
      - $MSFT_REPO_ROOT/src/sig_encode_z/config/design_lint/sig_encode_z/sglint_waivers
---
provides: [sigencode_z_tb]
schema_version: 2.4.0
requires:
  - sigencode_z
  - sigencode_z_pkg
targets:
  rtl:
    directories: [$COMPILE_ROOT/tb]
    files:
      - $COMPILE_ROOT/tb/sigencode_z_tb.sv
    tops: [sigencode_z_tb]
  sim:
    pre_exec: 'echo "[PRE-EXEC] Copying s1 bytes hex to $PWD" && cp $COMPILE_ROOT/tb/polyz_pack.py .'