---
provides: [abr_defines]
schema_version: 2.4.0
targets:
  tb:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/config_defines.svh
      - $COMPILE_ROOT/rtl/adamsbridge_reg_pkg.sv
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/config_defines.svh
      - $COMPILE_ROOT/rtl/adamsbridge_reg_pkg.sv
---
provides: [embedded_top]
schema_version: 2.4.0
requires:
  - abr_defines
  - abr_libs
  - rej_bounded
  - rej_sampler
  - exp_mask
  - sample_in_ball
  - sha3
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/embedded_top.sv
      - $COMPILE_ROOT/rtl/adamsbridge_reg.sv
    tops: [embedded_top]
  rtl_lint:
    waiver_files: []
    options: []
global:
  tool:
    vcs:
      default:
        - '-assert svaext'