# Copyright (C) Microsoft Corporation. All rights reserved.

# Go here for details on compile.yml syntax:
# https://dev.azure.com/ms-tsd/Ether/_git/sim-tools?path=%2FSourceFileSpec.docx&version=GBmaster

---
provides: [barrett_reduction]
schema_version: 2.4.0
requires:
  - abr_defines
  - ntt_pkg
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/barrett_reduction.sv
      # - $COMPILE_ROOT/rtl/masked_barrett_if_cond.sv
      - $COMPILE_ROOT/rtl/masked_barrett_reduction.sv
      - $COMPILE_ROOT/rtl/masked_barrett_if_cond_v2.sv
    tops: [barrett_reduction]
  rtl_lint:
    directories: []
    waiver_files: []
---
provides: [mlkem_barrett_reduction_tb]
schema_version: 2.4.0
requires:
  - barrett_reduction
targets:
  tb:
    directories: [$COMPILE_ROOT/tb]
    files:
      - $COMPILE_ROOT/tb/mlkem_barrett_reduction_tb.sv
    tops: [mlkem_barrett_reduction_tb]
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        - +define+CLP_ASSERT_ON
        - '-noinherit_timescale=1ns/1ps'
---
provides: [mldsa_barrett_reduction_tb]
schema_version: 2.4.0
requires:
  - barrett_reduction
targets:
  tb:
    directories: [$COMPILE_ROOT/tb]
    files:
      - $COMPILE_ROOT/tb/mldsa_barrett_reduction_tb.sv
    tops: [mldsa_barrett_reduction_tb]
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        - +define+CLP_ASSERT_ON
        - '-noinherit_timescale=1ns/1ps'
      
