uvmf:
  environments:
    mldsa:
      agents: []
      analysis_components:
      - name: mldsa_pred
        parameters: []
        type: mldsa_predictor
      - name: mldsa_sb
        parameters: []
        type: mldsa_scoreboard
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: mvc_pkg
      - name: mgc_ahb_v2_0_pkg
      - name: rw_txn_pkg
      non_uvmf_components: []
      parameters: []
      qvip_connections:
      - ap_key: burst_transfer
        driver: qvip_ahb_lite_slave_subenv_ahb_lite_slave_0
        receiver: mldsa_pred.ahb_slave_0_ae
        validate: 'false'
      - ap_key: trans_ap
        driver: qvip_ahb_lite_slave_subenv_ahb_lite_slave_0
        receiver: mldsa_sb.actual_ahb_analysis_export
        validate: 'false'
      qvip_memory_agents: []
      qvip_subenvs:
      - name: qvip_ahb_lite_slave_subenv
        type: qvip_ahb_lite_slave
      register_model:
        maps:
        - interface: qvip_ahb_lite_slave_subenv.ahb_lite_slave_0
          name: fixme_map
          qvip_agent: 'True'
        reg_block_class: mldsa_reg_model_top
        reg_model_package: mldsa_reg_model_top_pkg
        use_adapter: 'True'
        use_explicit_prediction: 'True'
      scoreboards: []
      subenvs: []
      tlm_connections:
      - driver: mldsa_pred.mldsa_sb_ahb_ap
        receiver: mldsa_sb.expected_ahb_analysis_export
        validate: 'false'
