---
provides: [mldsa_defines]
schema_version: 2.4.0
targets:
  tb:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/mldsa_config_defines.svh
      - $COMPILE_ROOT/rtl/mldsa_params_pkg.sv
      - $COMPILE_ROOT/rtl/mldsa_reg_pkg.sv
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/mldsa_config_defines.svh
      - $COMPILE_ROOT/rtl/mldsa_params_pkg.sv
      - $COMPILE_ROOT/rtl/mldsa_reg_pkg.sv
---
provides: [mldsa_top]
schema_version: 2.4.0
requires:
  - mldsa_defines
  - abr_libs
  - mldsa_sampler_top
  - ntt_top
  - decompose
  - skencode
  - skdecode
  - makehint
  - norm_check
  - sigencode_z
  - sigdecode_h
  - sigdecode_z
  - pkdecode
  - power2round
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/mldsa_ctrl_pkg.sv
      - $COMPILE_ROOT/rtl/mldsa_seq_prim.sv
      - $COMPILE_ROOT/rtl/mldsa_seq_sec.sv
      - $COMPILE_ROOT/rtl/mldsa_ctrl.sv
      - $COMPILE_ROOT/rtl/mldsa_top.sv
      - $COMPILE_ROOT/rtl/mldsa_reg.sv
    tops: [mldsa_top]
  rtl_lint:
  rtl_lint:
    waiver_files:
      - $MSFT_REPO_ROOT/src/mldsa_top/config/design_lint/sglint_waivers
    options: []
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
---
provides: [mldsa_top_tb]
schema_version: 2.4.0
requires:
  - mldsa_top
  - mldsa_defines
  - abr_libs
  - mldsa_sampler_top
targets:
  tb:
    directories: [$COMPILE_ROOT/tb]
    files:
      - $COMPILE_ROOT/tb/mldsa_top_tb.sv
    tops: [mldsa_top_tb]
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        - +define+ABR_ASSERT_ON
        - '-noinherit_timescale=1ns/1ps'