# Copyright (C) Microsoft Corporation. All rights reserved.

# Go here for details on compile.yml syntax:
# https://dev.azure.com/ms-tsd/Ether/_git/sim-tools?path=%2FSourceFileSpec.docx&version=GBmaster

---
provides: [ntt_pkg]
schema_version: 2.4.0
requires:
  - abr_defines
  - abr_libs
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/ntt_defines_pkg.sv
  tb:
    directories: 
      - $COMPILE_ROOT/rtl
    files:
      - $COMPILE_ROOT/rtl/ntt_defines_pkg.sv
---
provides: [butterfly_top_tb]  
schema_version: 2.4.0
requires: 
  - ntt_top
  - ntt_pkg
targets:
  tb:
    directories: 
      - $COMPILE_ROOT/tb
    files:
      - $COMPILE_ROOT/tb/butterfly_top_tb.sv
    tops: [butterfly_top_tb]
  sim:
    pre_exec: 'echo "[PRE-EXEC] Copying ntt hex to $PWD" && cp $COMPILE_ROOT/tb/test_vectors/kyber_zeta.txt . && cp $COMPILE_ROOT/tb/test_vectors/kyber_zeta_inv.hex . && cp $COMPILE_ROOT/tb/test_vectors/kyber_stage0.hex . && cp $COMPILE_ROOT/tb/test_vectors/kyber_stage0_out.hex . && cp $COMPILE_ROOT/tb/test_vectors/ntt_stage2.hex . && cp $COMPILE_ROOT/tb/test_vectors/ntt_stage2_out.hex .'
---
provides: [ntt_top]
schema_version: 2.4.0
requires:
  - ntt_pkg
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/ntt_butterfly2x2.sv
      - $COMPILE_ROOT/rtl/ntt_butterfly.sv
      - $COMPILE_ROOT/rtl/ntt_mult_dsp.sv
      - $COMPILE_ROOT/rtl/ntt_mult_reduction.sv
      - $COMPILE_ROOT/rtl/ntt_special_adder.sv
      - $COMPILE_ROOT/rtl/ntt_masked_special_adder.sv
      - $COMPILE_ROOT/rtl/ntt_masked_mult_redux46.sv
      - $COMPILE_ROOT/rtl/ntt_div2.sv
      - $COMPILE_ROOT/rtl/ntt_buffer.sv
      - $COMPILE_ROOT/rtl/ntt_shuffle_buffer.sv
      - $COMPILE_ROOT/rtl/ntt_twiddle_lookup.sv
      - $COMPILE_ROOT/rtl/ntt_ctrl.sv
      - $COMPILE_ROOT/rtl/ntt_top.sv
      - $COMPILE_ROOT/rtl/ntt_masked_BFU_add_sub.sv
      - $COMPILE_ROOT/rtl/ntt_masked_BFU_mult.sv
      - $COMPILE_ROOT/rtl/ntt_masked_gs_butterfly.sv
      - $COMPILE_ROOT/rtl/ntt_masked_pwm.sv
      - $COMPILE_ROOT/rtl/ntt_masked_butterfly1x2.sv
      - $COMPILE_ROOT/rtl/ntt_hybrid_butterfly_2x2.sv
      - $COMPILE_ROOT/../barrett_reduction/rtl/barrett_reduction.sv
      - $COMPILE_ROOT/rtl/ntt_karatsuba_pairwm.sv
  # tb:
  #   directories: [$COMPILE_ROOT/rtl]
  #   files:
  #     - $COMPILE_ROOT/tb/ntt_ram_tdp_file.sv
  #     - $COMPILE_ROOT/tb/ntt_wrapper.sv
      
    tops: [ntt_top]
  rtl_lint:
    directories: []
    waiver_files:
      - $MSFT_REPO_ROOT/src/ntt/config/design_lint/ntt_top/sglint_waivers
---
provides: [ntt_top_tb]  
schema_version: 2.4.0
requires: 
  - ntt_top
  - ntt_pkg
targets:
  rtl:
    directories: [$COMPILE_ROOT/tb]
    files:
      - $COMPILE_ROOT/tb/ntt_top_tb.sv
      - $COMPILE_ROOT/tb/ntt_ram_tdp_file.sv
      - $COMPILE_ROOT/tb/ntt_wrapper.sv
    tops: [ntt_top_tb]
  sim:
    pre_exec: 'echo "[PRE-EXEC] Copying ntt hex to $PWD" && cp $COMPILE_ROOT/tb/test_vectors/zeta.txt . && cp $COMPILE_ROOT/tb/test_vectors/zeta_inv.hex . && cp $COMPILE_ROOT/tb/test_vectors/ntt_stage0_mem.hex . && cp $COMPILE_ROOT/tb/test_vectors/rand_ntt_stage0_mem.hex . && cp $COMPILE_ROOT/tb/test_vectors/ntt_stage0_out.hex . && cp $COMPILE_ROOT/tb/test_vectors/ntt_stage67.hex . && cp $COMPILE_ROOT/tb/test_vectors/pwm_iter1.hex . && cp $COMPILE_ROOT/tb/test_vectors/pwm_iter2.hex .'

---
provides: [ntt_mult_reduction_tb]  
schema_version: 2.4.0
requires: 
  - ntt_top
targets:
  rtl:
    directories: [$COMPILE_ROOT/tb]
    files:
      - $COMPILE_ROOT/tb/ntt_mult_reduction_tb.sv
    tops: [ntt_mult_reduction_tb]

---
provides: [ntt_masked_mult_reduction_tb]  
schema_version: 2.4.0
requires: 
  - ntt_top
targets:
  rtl:
    directories: [$COMPILE_ROOT/tb]
    files:
      - $COMPILE_ROOT/tb/ntt_masked_mult_redux46_tb.sv
      - $COMPILE_ROOT/tb/ntt_masked_mult_redux46_auto_tb.sv
    tops: [ntt_masked_mult_redux46_auto_tb]

---
provides: [ntt_top_masking_tb]  
schema_version: 2.4.0
requires: 
  - ntt_top
targets:
  rtl:
    directories: [$COMPILE_ROOT/tb]
    files:
      - $COMPILE_ROOT/tb/ntt_top_masking_tb.sv
    tops: [ntt_top_masking_tb]

---
provides: [ntt_utb]  
schema_version: 2.4.0
requires:
  - mldsa_uvm_lib
  - ntt_top
  - ntt_pkg
targets:
  tb:
    directories: [$COMPILE_ROOT/utb]
    files:
      - $COMPILE_ROOT/utb/ntt_utb_top/ntt_utb_defines.sv
      - $COMPILE_ROOT/utb/interfaces/ntt_if.sv
      - $COMPILE_ROOT/utb/interfaces/mem_if.sv
      - $COMPILE_ROOT/utb/mem_agent/mem_txn.sv
      - $COMPILE_ROOT/utb/mem_agent/mem_agent_config.sv
      - $COMPILE_ROOT/utb/mem_agent/mem_sequencer.sv
      - $COMPILE_ROOT/utb/mem_agent/mem_driver.sv
      - $COMPILE_ROOT/utb/mem_agent/mem_mon.sv
      - $COMPILE_ROOT/utb/mem_agent/mem_agent.sv
      - $COMPILE_ROOT/utb/ntt_agent/ntt_txn.sv
      - $COMPILE_ROOT/utb/ntt_agent/ntt_sequencer.sv
      - $COMPILE_ROOT/utb/ntt_agent/ntt_driver.sv
      - $COMPILE_ROOT/utb/ntt_agent/ntt_mon.sv
      - $COMPILE_ROOT/utb/ntt_agent/ntt_agent.sv
      - $COMPILE_ROOT/utb/scoreboard/ntt_sb.sv
      - $COMPILE_ROOT/utb/env/ntt_env.sv
      - $COMPILE_ROOT/utb/sequences/ntt_seq/ntt_base_seq.sv
      - $COMPILE_ROOT/utb/sequences/ntt_seq/ntt_fwd_seq.sv
      - $COMPILE_ROOT/utb/sequences/ntt_seq/ntt_inv_seq.sv
      - $COMPILE_ROOT/utb/sequences/ntt_seq_lib.sv
      - $COMPILE_ROOT/utb/sequences/mem_seq_lib.sv
      - $COMPILE_ROOT/utb/sequences/ntt_virtual_seq.sv
      - $COMPILE_ROOT/utb/tests/ntt_base_test.sv
      - $COMPILE_ROOT/utb/tests/ntt_combined_test.sv
      - $COMPILE_ROOT/utb/ntt_utb_top/ntt_utb_top.sv
      - $COMPILE_ROOT/tb/ntt_ram_tdp_file.sv
      - $COMPILE_ROOT/tb/ntt_wrapper.sv
    tops: [ntt_utb_top]
