---
provides: [uvmf_mldsa]
schema_version: 2.4.0
requires:
  - uvmf_lib
  - mldsa_top
targets:
  tb:
    directories:
      - ${COMPILE_ROOT}
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/environment_packages/mldsa_env_pkg
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/environment_packages/mldsa_env_pkg/registers
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/mldsa/tb/parameters
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/mldsa/tb/sequences
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/mldsa/tb/tests
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/mldsa/tb/testbench
    files:
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/environment_packages/mldsa_env_pkg/registers/mldsa_reg_uvm.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/environment_packages/mldsa_env_pkg/registers/mldsa_reg_model_top_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/verification_ip/environment_packages/mldsa_env_pkg/mldsa_env_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/mldsa/tb/parameters/mldsa_parameters_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/mldsa/tb/sequences/mldsa_sequences_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/mldsa/tb/tests/mldsa_tests_pkg.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/mldsa/tb/testbench/hdl_top.sv
      - ${COMPILE_ROOT}/uvmf_template_output/project_benches/mldsa/tb/testbench/hvl_top.sv
    tops:
      - hdl_top
      - hvl_top
  sim:
    pre_exec: 'echo "[PRE-EXEC] Copying C executbale vector generator to $PWD" && cp $COMPILE_ROOT/uvmf_template_output/verification_ip/environment_packages/mldsa_env_pkg/src/test_dilithium5 . && cp $COMPILE_ROOT/uvmf_template_output/verification_ip/environment_packages/mldsa_env_pkg/src/test_dilithium5_debug .'  
global:
  tool:
    vcs:
      default:
        - '-assert svaext'
        - +define+ABR_ASSERT_ON
        #- '-v2k_generate'
        #- '-timescale=1ns/1ps'
        - '-noinherit_timescale=1ns/1ps'
        #- '-ucli -i dump.ucli'
      #sim:
        #- '-ucli -i dump.ucli'
        # Suppress a warning due to calling $fgets as task instead of function
        # i.e. discarding the return value. This is in auto-generated code.
        - '+warn=noRVOSFD'
        # Suppress NOTE about repeated package imports within the same
        # package (each .svh file included in the auto-generated UVM _pkg.sv
        # files imports the same dependencies)
        - '-suppress=SV-LCM-PPWI'
      elab:
        # Suppress warnings about too few port connections - auto-generated interfaces
        # declare all signals as inout, but are driven at a lower layer than the
        # instantiation, so they will always flag this
        - '-suppress=TFIPC'
      sim:
        - '-sv_root $QUESTA_MVC_HOME/questa_mvc_core/linux_x86_64_gcc-6.2.0_vcs'
        - '-sv_lib libahb_IN_SystemVerilog_VCS_full'
        - '-sv_lib libapb3_IN_SystemVerilog_VCS_full'
        # Report "MVC_ERROR" as "UVM_ERROR"
        - '+QVIP_UVM_REPORTING'
