
// This file was autogenerated by PeakRDL-uvm
package abr_reg_uvm;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    `include "abr_reg_covergroups.svh"
    // Reg - abr_reg::MLDSA_NAME
    class abr_reg__MLDSA_NAME extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLDSA_NAME_bit_cg NAME_bit_cg[32];
        abr_reg__MLDSA_NAME_fld_cg fld_cg;
        rand uvm_reg_field NAME;

        function new(string name = "abr_reg__MLDSA_NAME");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.NAME = new("NAME");
            this.NAME.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(NAME_bit_cg[bt]) NAME_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLDSA_NAME

    // Reg - abr_reg::MLDSA_VERSION
    class abr_reg__MLDSA_VERSION extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLDSA_VERSION_bit_cg VERSION_bit_cg[32];
        abr_reg__MLDSA_VERSION_fld_cg fld_cg;
        rand uvm_reg_field VERSION;

        function new(string name = "abr_reg__MLDSA_VERSION");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.VERSION = new("VERSION");
            this.VERSION.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(VERSION_bit_cg[bt]) VERSION_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLDSA_VERSION

    // Reg - abr_reg::MLDSA_CTRL
    class abr_reg__MLDSA_CTRL extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLDSA_CTRL_bit_cg CTRL_bit_cg[3];
        abr_reg__MLDSA_CTRL_bit_cg ZEROIZE_bit_cg[1];
        abr_reg__MLDSA_CTRL_bit_cg PCR_SIGN_bit_cg[1];
        abr_reg__MLDSA_CTRL_bit_cg EXTERNAL_MU_bit_cg[1];
        abr_reg__MLDSA_CTRL_bit_cg STREAM_MSG_bit_cg[1];
        abr_reg__MLDSA_CTRL_fld_cg fld_cg;
        rand uvm_reg_field CTRL;
        rand uvm_reg_field ZEROIZE;
        rand uvm_reg_field PCR_SIGN;
        rand uvm_reg_field EXTERNAL_MU;
        rand uvm_reg_field STREAM_MSG;

        function new(string name = "abr_reg__MLDSA_CTRL");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.CTRL = new("CTRL");
            this.CTRL.configure(this, 3, 0, "WO", 1, 'h0, 1, 1, 0);
            this.ZEROIZE = new("ZEROIZE");
            this.ZEROIZE.configure(this, 1, 3, "WO", 0, 'h0, 1, 1, 0);
            this.PCR_SIGN = new("PCR_SIGN");
            this.PCR_SIGN.configure(this, 1, 4, "WO", 1, 'h0, 1, 1, 0);
            this.EXTERNAL_MU = new("EXTERNAL_MU");
            this.EXTERNAL_MU.configure(this, 1, 5, "WO", 1, 'h0, 1, 1, 0);
            this.STREAM_MSG = new("STREAM_MSG");
            this.STREAM_MSG.configure(this, 1, 6, "WO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(CTRL_bit_cg[bt]) CTRL_bit_cg[bt] = new();
                foreach(ZEROIZE_bit_cg[bt]) ZEROIZE_bit_cg[bt] = new();
                foreach(PCR_SIGN_bit_cg[bt]) PCR_SIGN_bit_cg[bt] = new();
                foreach(EXTERNAL_MU_bit_cg[bt]) EXTERNAL_MU_bit_cg[bt] = new();
                foreach(STREAM_MSG_bit_cg[bt]) STREAM_MSG_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLDSA_CTRL

    // Reg - abr_reg::MLDSA_STATUS
    class abr_reg__MLDSA_STATUS extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLDSA_STATUS_bit_cg READY_bit_cg[1];
        abr_reg__MLDSA_STATUS_bit_cg VALID_bit_cg[1];
        abr_reg__MLDSA_STATUS_bit_cg MSG_STREAM_READY_bit_cg[1];
        abr_reg__MLDSA_STATUS_fld_cg fld_cg;
        rand uvm_reg_field READY;
        rand uvm_reg_field VALID;
        rand uvm_reg_field MSG_STREAM_READY;

        function new(string name = "abr_reg__MLDSA_STATUS");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.READY = new("READY");
            this.READY.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.VALID = new("VALID");
            this.VALID.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 0);
            this.MSG_STREAM_READY = new("MSG_STREAM_READY");
            this.MSG_STREAM_READY.configure(this, 1, 2, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(READY_bit_cg[bt]) READY_bit_cg[bt] = new();
                foreach(VALID_bit_cg[bt]) VALID_bit_cg[bt] = new();
                foreach(MSG_STREAM_READY_bit_cg[bt]) MSG_STREAM_READY_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLDSA_STATUS

    // Reg - abr_reg::ABR_ENTROPY
    class abr_reg__ABR_ENTROPY extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__ABR_ENTROPY_bit_cg ENTROPY_bit_cg[32];
        abr_reg__ABR_ENTROPY_fld_cg fld_cg;
        rand uvm_reg_field ENTROPY;

        function new(string name = "abr_reg__ABR_ENTROPY");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.ENTROPY = new("ENTROPY");
            this.ENTROPY.configure(this, 32, 0, "WO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(ENTROPY_bit_cg[bt]) ENTROPY_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__ABR_ENTROPY

    // Reg - abr_reg::MLDSA_SEED
    class abr_reg__MLDSA_SEED extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLDSA_SEED_bit_cg SEED_bit_cg[32];
        abr_reg__MLDSA_SEED_fld_cg fld_cg;
        rand uvm_reg_field SEED;

        function new(string name = "abr_reg__MLDSA_SEED");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.SEED = new("SEED");
            this.SEED.configure(this, 32, 0, "WO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(SEED_bit_cg[bt]) SEED_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLDSA_SEED

    // Reg - abr_reg::MLDSA_SIGN_RND
    class abr_reg__MLDSA_SIGN_RND extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLDSA_SIGN_RND_bit_cg SIGN_RND_bit_cg[32];
        abr_reg__MLDSA_SIGN_RND_fld_cg fld_cg;
        rand uvm_reg_field SIGN_RND;

        function new(string name = "abr_reg__MLDSA_SIGN_RND");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.SIGN_RND = new("SIGN_RND");
            this.SIGN_RND.configure(this, 32, 0, "WO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(SIGN_RND_bit_cg[bt]) SIGN_RND_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLDSA_SIGN_RND

    // Reg - abr_reg::MLDSA_MSG
    class abr_reg__MLDSA_MSG extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLDSA_MSG_bit_cg MSG_bit_cg[32];
        abr_reg__MLDSA_MSG_fld_cg fld_cg;
        rand uvm_reg_field MSG;

        function new(string name = "abr_reg__MLDSA_MSG");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.MSG = new("MSG");
            this.MSG.configure(this, 32, 0, "WO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(MSG_bit_cg[bt]) MSG_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLDSA_MSG

    // Reg - abr_reg::MLDSA_VERIFY_RES
    class abr_reg__MLDSA_VERIFY_RES extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLDSA_VERIFY_RES_bit_cg VERIFY_RES_bit_cg[32];
        abr_reg__MLDSA_VERIFY_RES_fld_cg fld_cg;
        rand uvm_reg_field VERIFY_RES;

        function new(string name = "abr_reg__MLDSA_VERIFY_RES");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.VERIFY_RES = new("VERIFY_RES");
            this.VERIFY_RES.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(VERIFY_RES_bit_cg[bt]) VERIFY_RES_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLDSA_VERIFY_RES

    // Reg - abr_reg::MLDSA_EXTERNAL_MU
    class abr_reg__MLDSA_EXTERNAL_MU extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLDSA_EXTERNAL_MU_bit_cg EXTERNAL_MU_bit_cg[32];
        abr_reg__MLDSA_EXTERNAL_MU_fld_cg fld_cg;
        rand uvm_reg_field EXTERNAL_MU;

        function new(string name = "abr_reg__MLDSA_EXTERNAL_MU");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.EXTERNAL_MU = new("EXTERNAL_MU");
            this.EXTERNAL_MU.configure(this, 32, 0, "WO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(EXTERNAL_MU_bit_cg[bt]) EXTERNAL_MU_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLDSA_EXTERNAL_MU

    // Reg - abr_reg::MLDSA_MSG_STROBE
    class abr_reg__MLDSA_MSG_STROBE extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLDSA_MSG_STROBE_bit_cg STROBE_bit_cg[4];
        abr_reg__MLDSA_MSG_STROBE_fld_cg fld_cg;
        rand uvm_reg_field STROBE;

        function new(string name = "abr_reg__MLDSA_MSG_STROBE");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.STROBE = new("STROBE");
            this.STROBE.configure(this, 4, 0, "WO", 1, 'hf, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(STROBE_bit_cg[bt]) STROBE_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLDSA_MSG_STROBE

    // Reg - abr_reg::MLDSA_CTX_CONFIG
    class abr_reg__MLDSA_CTX_CONFIG extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLDSA_CTX_CONFIG_bit_cg CTX_SIZE_bit_cg[8];
        abr_reg__MLDSA_CTX_CONFIG_fld_cg fld_cg;
        rand uvm_reg_field CTX_SIZE;

        function new(string name = "abr_reg__MLDSA_CTX_CONFIG");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.CTX_SIZE = new("CTX_SIZE");
            this.CTX_SIZE.configure(this, 8, 0, "WO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(CTX_SIZE_bit_cg[bt]) CTX_SIZE_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLDSA_CTX_CONFIG

    // Reg - abr_reg::MLDSA_CTX
    class abr_reg__MLDSA_CTX extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLDSA_CTX_bit_cg CTX_bit_cg[32];
        abr_reg__MLDSA_CTX_fld_cg fld_cg;
        rand uvm_reg_field CTX;

        function new(string name = "abr_reg__MLDSA_CTX");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.CTX = new("CTX");
            this.CTX.configure(this, 32, 0, "WO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(CTX_bit_cg[bt]) CTX_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLDSA_CTX

    // Mem - abr_reg::MLDSA_PUBKEY
    class abr_reg__MLDSA_PUBKEY extends uvm_reg_block;
        rand uvm_mem m_mem;
        
        function new(string name = "abr_reg__MLDSA_PUBKEY");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4.0, UVM_NO_ENDIAN);
            this.m_mem = new("m_mem", 648, 32, "RW");
            this.m_mem.configure(this);
            this.default_map.add_mem(this.m_mem, 0);
        endfunction : build
    endclass : abr_reg__MLDSA_PUBKEY

    // Mem - abr_reg::MLDSA_SIGNATURE
    class abr_reg__MLDSA_SIGNATURE extends uvm_reg_block;
        rand uvm_mem m_mem;
        
        function new(string name = "abr_reg__MLDSA_SIGNATURE");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4.0, UVM_NO_ENDIAN);
            this.m_mem = new("m_mem", 1157, 32, "RW");
            this.m_mem.configure(this);
            this.default_map.add_mem(this.m_mem, 0);
        endfunction : build
    endclass : abr_reg__MLDSA_SIGNATURE

    // Mem - abr_reg::MLDSA_PRIVKEY_OUT
    class abr_reg__MLDSA_PRIVKEY_OUT extends uvm_reg_block;
        rand uvm_mem m_mem;
        
        function new(string name = "abr_reg__MLDSA_PRIVKEY_OUT");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4.0, UVM_NO_ENDIAN);
            this.m_mem = new("m_mem", 1224, 32, "RO");
            this.m_mem.configure(this);
            this.default_map.add_mem(this.m_mem, 0);
        endfunction : build
    endclass : abr_reg__MLDSA_PRIVKEY_OUT

    // Mem - abr_reg::MLDSA_PRIVKEY_IN
    class abr_reg__MLDSA_PRIVKEY_IN extends uvm_reg_block;
        rand uvm_mem m_mem;
        
        function new(string name = "abr_reg__MLDSA_PRIVKEY_IN");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4.0, UVM_NO_ENDIAN);
            this.m_mem = new("m_mem", 1224, 32, "RW");
            this.m_mem.configure(this);
            this.default_map.add_mem(this.m_mem, 0);
        endfunction : build
    endclass : abr_reg__MLDSA_PRIVKEY_IN

    // Reg - kv_read_ctrl_reg
    class kv_read_ctrl_reg extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        kv_read_ctrl_reg_bit_cg read_en_bit_cg[1];
        kv_read_ctrl_reg_bit_cg read_entry_bit_cg[5];
        kv_read_ctrl_reg_bit_cg pcr_hash_extend_bit_cg[1];
        kv_read_ctrl_reg_bit_cg rsvd_bit_cg[25];
        kv_read_ctrl_reg_fld_cg fld_cg;
        rand uvm_reg_field read_en;
        rand uvm_reg_field read_entry;
        rand uvm_reg_field pcr_hash_extend;
        rand uvm_reg_field rsvd;

        function new(string name = "kv_read_ctrl_reg");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.read_en = new("read_en");
            this.read_en.configure(this, 1, 0, "RW", 1, 'h0, 1, 1, 0);
            this.read_entry = new("read_entry");
            this.read_entry.configure(this, 5, 1, "RW", 0, 'h0, 1, 1, 0);
            this.pcr_hash_extend = new("pcr_hash_extend");
            this.pcr_hash_extend.configure(this, 1, 6, "RW", 0, 'h0, 1, 1, 0);
            this.rsvd = new("rsvd");
            this.rsvd.configure(this, 25, 7, "RW", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(read_en_bit_cg[bt]) read_en_bit_cg[bt] = new();
                foreach(read_entry_bit_cg[bt]) read_entry_bit_cg[bt] = new();
                foreach(pcr_hash_extend_bit_cg[bt]) pcr_hash_extend_bit_cg[bt] = new();
                foreach(rsvd_bit_cg[bt]) rsvd_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : kv_read_ctrl_reg

    // Reg - kv_status_reg
    class kv_status_reg extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        kv_status_reg_bit_cg READY_bit_cg[1];
        kv_status_reg_bit_cg VALID_bit_cg[1];
        kv_status_reg_bit_cg ERROR_bit_cg[8];
        kv_status_reg_fld_cg fld_cg;
        rand uvm_reg_field READY;
        rand uvm_reg_field VALID;
        rand uvm_reg_field ERROR;

        function new(string name = "kv_status_reg");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.READY = new("READY");
            this.READY.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.VALID = new("VALID");
            this.VALID.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 0);
            this.ERROR = new("ERROR");
            this.ERROR.configure(this, 8, 2, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(READY_bit_cg[bt]) READY_bit_cg[bt] = new();
                foreach(VALID_bit_cg[bt]) VALID_bit_cg[bt] = new();
                foreach(ERROR_bit_cg[bt]) ERROR_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : kv_status_reg

    // Reg - abr_reg::MLKEM_NAME
    class abr_reg__MLKEM_NAME extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLKEM_NAME_bit_cg NAME_bit_cg[32];
        abr_reg__MLKEM_NAME_fld_cg fld_cg;
        rand uvm_reg_field NAME;

        function new(string name = "abr_reg__MLKEM_NAME");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.NAME = new("NAME");
            this.NAME.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(NAME_bit_cg[bt]) NAME_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLKEM_NAME

    // Reg - abr_reg::MLKEM_VERSION
    class abr_reg__MLKEM_VERSION extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLKEM_VERSION_bit_cg VERSION_bit_cg[32];
        abr_reg__MLKEM_VERSION_fld_cg fld_cg;
        rand uvm_reg_field VERSION;

        function new(string name = "abr_reg__MLKEM_VERSION");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.VERSION = new("VERSION");
            this.VERSION.configure(this, 32, 0, "RO", 1, 'h0, 0, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(VERSION_bit_cg[bt]) VERSION_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLKEM_VERSION

    // Reg - abr_reg::MLKEM_CTRL
    class abr_reg__MLKEM_CTRL extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLKEM_CTRL_bit_cg CTRL_bit_cg[3];
        abr_reg__MLKEM_CTRL_bit_cg ZEROIZE_bit_cg[1];
        abr_reg__MLKEM_CTRL_fld_cg fld_cg;
        rand uvm_reg_field CTRL;
        rand uvm_reg_field ZEROIZE;

        function new(string name = "abr_reg__MLKEM_CTRL");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.CTRL = new("CTRL");
            this.CTRL.configure(this, 3, 0, "WO", 1, 'h0, 1, 1, 0);
            this.ZEROIZE = new("ZEROIZE");
            this.ZEROIZE.configure(this, 1, 3, "WO", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(CTRL_bit_cg[bt]) CTRL_bit_cg[bt] = new();
                foreach(ZEROIZE_bit_cg[bt]) ZEROIZE_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLKEM_CTRL

    // Reg - abr_reg::MLKEM_STATUS
    class abr_reg__MLKEM_STATUS extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLKEM_STATUS_bit_cg READY_bit_cg[1];
        abr_reg__MLKEM_STATUS_bit_cg VALID_bit_cg[1];
        abr_reg__MLKEM_STATUS_fld_cg fld_cg;
        rand uvm_reg_field READY;
        rand uvm_reg_field VALID;

        function new(string name = "abr_reg__MLKEM_STATUS");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.READY = new("READY");
            this.READY.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.VALID = new("VALID");
            this.VALID.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(READY_bit_cg[bt]) READY_bit_cg[bt] = new();
                foreach(VALID_bit_cg[bt]) VALID_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLKEM_STATUS

    // Reg - abr_reg::MLKEM_SEED_D
    class abr_reg__MLKEM_SEED_D extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLKEM_SEED_D_bit_cg SEED_bit_cg[32];
        abr_reg__MLKEM_SEED_D_fld_cg fld_cg;
        rand uvm_reg_field SEED;

        function new(string name = "abr_reg__MLKEM_SEED_D");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.SEED = new("SEED");
            this.SEED.configure(this, 32, 0, "WO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(SEED_bit_cg[bt]) SEED_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLKEM_SEED_D

    // Reg - abr_reg::MLKEM_SEED_Z
    class abr_reg__MLKEM_SEED_Z extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLKEM_SEED_Z_bit_cg SEED_bit_cg[32];
        abr_reg__MLKEM_SEED_Z_fld_cg fld_cg;
        rand uvm_reg_field SEED;

        function new(string name = "abr_reg__MLKEM_SEED_Z");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.SEED = new("SEED");
            this.SEED.configure(this, 32, 0, "WO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(SEED_bit_cg[bt]) SEED_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLKEM_SEED_Z

    // Reg - abr_reg::MLKEM_SHARED_KEY
    class abr_reg__MLKEM_SHARED_KEY extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__MLKEM_SHARED_KEY_bit_cg KEY_bit_cg[32];
        abr_reg__MLKEM_SHARED_KEY_fld_cg fld_cg;
        rand uvm_reg_field KEY;

        function new(string name = "abr_reg__MLKEM_SHARED_KEY");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.KEY = new("KEY");
            this.KEY.configure(this, 32, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(KEY_bit_cg[bt]) KEY_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__MLKEM_SHARED_KEY

    // Mem - abr_reg::MLKEM_MSG
    class abr_reg__MLKEM_MSG extends uvm_reg_block;
        rand uvm_mem m_mem;
        
        function new(string name = "abr_reg__MLKEM_MSG");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4.0, UVM_NO_ENDIAN);
            this.m_mem = new("m_mem", 8, 32, "RW");
            this.m_mem.configure(this);
            this.default_map.add_mem(this.m_mem, 0);
        endfunction : build
    endclass : abr_reg__MLKEM_MSG

    // Mem - abr_reg::MLKEM_DECAPS_KEY
    class abr_reg__MLKEM_DECAPS_KEY extends uvm_reg_block;
        rand uvm_mem m_mem;
        
        function new(string name = "abr_reg__MLKEM_DECAPS_KEY");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4.0, UVM_NO_ENDIAN);
            this.m_mem = new("m_mem", 792, 32, "RW");
            this.m_mem.configure(this);
            this.default_map.add_mem(this.m_mem, 0);
        endfunction : build
    endclass : abr_reg__MLKEM_DECAPS_KEY

    // Mem - abr_reg::MLKEM_ENCAPS_KEY
    class abr_reg__MLKEM_ENCAPS_KEY extends uvm_reg_block;
        rand uvm_mem m_mem;
        
        function new(string name = "abr_reg__MLKEM_ENCAPS_KEY");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4.0, UVM_NO_ENDIAN);
            this.m_mem = new("m_mem", 392, 32, "RW");
            this.m_mem.configure(this);
            this.default_map.add_mem(this.m_mem, 0);
        endfunction : build
    endclass : abr_reg__MLKEM_ENCAPS_KEY

    // Mem - abr_reg::MLKEM_CIPHERTEXT
    class abr_reg__MLKEM_CIPHERTEXT extends uvm_reg_block;
        rand uvm_mem m_mem;
        
        function new(string name = "abr_reg__MLKEM_CIPHERTEXT");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4.0, UVM_NO_ENDIAN);
            this.m_mem = new("m_mem", 392, 32, "RW");
            this.m_mem.configure(this);
            this.default_map.add_mem(this.m_mem, 0);
        endfunction : build
    endclass : abr_reg__MLKEM_CIPHERTEXT

    // Reg - kv_write_ctrl_reg
    class kv_write_ctrl_reg extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        kv_write_ctrl_reg_bit_cg write_en_bit_cg[1];
        kv_write_ctrl_reg_bit_cg write_entry_bit_cg[5];
        kv_write_ctrl_reg_bit_cg hmac_key_dest_valid_bit_cg[1];
        kv_write_ctrl_reg_bit_cg hmac_block_dest_valid_bit_cg[1];
        kv_write_ctrl_reg_bit_cg mldsa_seed_dest_valid_bit_cg[1];
        kv_write_ctrl_reg_bit_cg ecc_pkey_dest_valid_bit_cg[1];
        kv_write_ctrl_reg_bit_cg ecc_seed_dest_valid_bit_cg[1];
        kv_write_ctrl_reg_bit_cg aes_key_dest_valid_bit_cg[1];
        kv_write_ctrl_reg_bit_cg mlkem_seed_dest_valid_bit_cg[1];
        kv_write_ctrl_reg_bit_cg mlkem_msg_dest_valid_bit_cg[1];
        kv_write_ctrl_reg_bit_cg rsvd_bit_cg[18];
        kv_write_ctrl_reg_fld_cg fld_cg;
        rand uvm_reg_field write_en;
        rand uvm_reg_field write_entry;
        rand uvm_reg_field hmac_key_dest_valid;
        rand uvm_reg_field hmac_block_dest_valid;
        rand uvm_reg_field mldsa_seed_dest_valid;
        rand uvm_reg_field ecc_pkey_dest_valid;
        rand uvm_reg_field ecc_seed_dest_valid;
        rand uvm_reg_field aes_key_dest_valid;
        rand uvm_reg_field mlkem_seed_dest_valid;
        rand uvm_reg_field mlkem_msg_dest_valid;
        rand uvm_reg_field rsvd;

        function new(string name = "kv_write_ctrl_reg");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.write_en = new("write_en");
            this.write_en.configure(this, 1, 0, "RW", 1, 'h0, 1, 1, 0);
            this.write_entry = new("write_entry");
            this.write_entry.configure(this, 5, 1, "RW", 0, 'h0, 1, 1, 0);
            this.hmac_key_dest_valid = new("hmac_key_dest_valid");
            this.hmac_key_dest_valid.configure(this, 1, 6, "RW", 0, 'h0, 1, 1, 0);
            this.hmac_block_dest_valid = new("hmac_block_dest_valid");
            this.hmac_block_dest_valid.configure(this, 1, 7, "RW", 0, 'h0, 1, 1, 0);
            this.mldsa_seed_dest_valid = new("mldsa_seed_dest_valid");
            this.mldsa_seed_dest_valid.configure(this, 1, 8, "RW", 0, 'h0, 1, 1, 0);
            this.ecc_pkey_dest_valid = new("ecc_pkey_dest_valid");
            this.ecc_pkey_dest_valid.configure(this, 1, 9, "RW", 0, 'h0, 1, 1, 0);
            this.ecc_seed_dest_valid = new("ecc_seed_dest_valid");
            this.ecc_seed_dest_valid.configure(this, 1, 10, "RW", 0, 'h0, 1, 1, 0);
            this.aes_key_dest_valid = new("aes_key_dest_valid");
            this.aes_key_dest_valid.configure(this, 1, 11, "RW", 0, 'h0, 1, 1, 0);
            this.mlkem_seed_dest_valid = new("mlkem_seed_dest_valid");
            this.mlkem_seed_dest_valid.configure(this, 1, 12, "RW", 0, 'h0, 1, 1, 0);
            this.mlkem_msg_dest_valid = new("mlkem_msg_dest_valid");
            this.mlkem_msg_dest_valid.configure(this, 1, 13, "RW", 0, 'h0, 1, 1, 0);
            this.rsvd = new("rsvd");
            this.rsvd.configure(this, 18, 14, "RW", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(write_en_bit_cg[bt]) write_en_bit_cg[bt] = new();
                foreach(write_entry_bit_cg[bt]) write_entry_bit_cg[bt] = new();
                foreach(hmac_key_dest_valid_bit_cg[bt]) hmac_key_dest_valid_bit_cg[bt] = new();
                foreach(hmac_block_dest_valid_bit_cg[bt]) hmac_block_dest_valid_bit_cg[bt] = new();
                foreach(mldsa_seed_dest_valid_bit_cg[bt]) mldsa_seed_dest_valid_bit_cg[bt] = new();
                foreach(ecc_pkey_dest_valid_bit_cg[bt]) ecc_pkey_dest_valid_bit_cg[bt] = new();
                foreach(ecc_seed_dest_valid_bit_cg[bt]) ecc_seed_dest_valid_bit_cg[bt] = new();
                foreach(aes_key_dest_valid_bit_cg[bt]) aes_key_dest_valid_bit_cg[bt] = new();
                foreach(mlkem_seed_dest_valid_bit_cg[bt]) mlkem_seed_dest_valid_bit_cg[bt] = new();
                foreach(mlkem_msg_dest_valid_bit_cg[bt]) mlkem_msg_dest_valid_bit_cg[bt] = new();
                foreach(rsvd_bit_cg[bt]) rsvd_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : kv_write_ctrl_reg

    // Reg - abr_reg::intr_block_t::global_intr_en_t
    class abr_reg__intr_block_t__global_intr_en_t extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__intr_block_t__global_intr_en_t_bit_cg error_en_bit_cg[1];
        abr_reg__intr_block_t__global_intr_en_t_bit_cg notif_en_bit_cg[1];
        abr_reg__intr_block_t__global_intr_en_t_fld_cg fld_cg;
        rand uvm_reg_field error_en;
        rand uvm_reg_field notif_en;

        function new(string name = "abr_reg__intr_block_t__global_intr_en_t");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.error_en = new("error_en");
            this.error_en.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.notif_en = new("notif_en");
            this.notif_en.configure(this, 1, 1, "RW", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(error_en_bit_cg[bt]) error_en_bit_cg[bt] = new();
                foreach(notif_en_bit_cg[bt]) notif_en_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__intr_block_t__global_intr_en_t

    // Reg - abr_reg::intr_block_t::error_intr_en_t
    class abr_reg__intr_block_t__error_intr_en_t extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__intr_block_t__error_intr_en_t_bit_cg error_internal_en_bit_cg[1];
        abr_reg__intr_block_t__error_intr_en_t_fld_cg fld_cg;
        rand uvm_reg_field error_internal_en;

        function new(string name = "abr_reg__intr_block_t__error_intr_en_t");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.error_internal_en = new("error_internal_en");
            this.error_internal_en.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(error_internal_en_bit_cg[bt]) error_internal_en_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__intr_block_t__error_intr_en_t

    // Reg - abr_reg::intr_block_t::notif_intr_en_t
    class abr_reg__intr_block_t__notif_intr_en_t extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__intr_block_t__notif_intr_en_t_bit_cg notif_cmd_done_en_bit_cg[1];
        abr_reg__intr_block_t__notif_intr_en_t_fld_cg fld_cg;
        rand uvm_reg_field notif_cmd_done_en;

        function new(string name = "abr_reg__intr_block_t__notif_intr_en_t");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.notif_cmd_done_en = new("notif_cmd_done_en");
            this.notif_cmd_done_en.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(notif_cmd_done_en_bit_cg[bt]) notif_cmd_done_en_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__intr_block_t__notif_intr_en_t

    // Reg - abr_reg::intr_block_t::global_intr_t_agg_sts_dd3dcf0a
    class abr_reg__intr_block_t__global_intr_t_agg_sts_dd3dcf0a extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__intr_block_t__global_intr_t_agg_sts_dd3dcf0a_bit_cg agg_sts_bit_cg[1];
        abr_reg__intr_block_t__global_intr_t_agg_sts_dd3dcf0a_fld_cg fld_cg;
        rand uvm_reg_field agg_sts;

        function new(string name = "abr_reg__intr_block_t__global_intr_t_agg_sts_dd3dcf0a");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.agg_sts = new("agg_sts");
            this.agg_sts.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(agg_sts_bit_cg[bt]) agg_sts_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__intr_block_t__global_intr_t_agg_sts_dd3dcf0a

    // Reg - abr_reg::intr_block_t::global_intr_t_agg_sts_e6399b4a
    class abr_reg__intr_block_t__global_intr_t_agg_sts_e6399b4a extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__intr_block_t__global_intr_t_agg_sts_e6399b4a_bit_cg agg_sts_bit_cg[1];
        abr_reg__intr_block_t__global_intr_t_agg_sts_e6399b4a_fld_cg fld_cg;
        rand uvm_reg_field agg_sts;

        function new(string name = "abr_reg__intr_block_t__global_intr_t_agg_sts_e6399b4a");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.agg_sts = new("agg_sts");
            this.agg_sts.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(agg_sts_bit_cg[bt]) agg_sts_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__intr_block_t__global_intr_t_agg_sts_e6399b4a

    // Reg - abr_reg::intr_block_t::error_intr_t_error_internal_sts_83adab02
    class abr_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02_bit_cg error_internal_sts_bit_cg[1];
        abr_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02_fld_cg fld_cg;
        rand uvm_reg_field error_internal_sts;

        function new(string name = "abr_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.error_internal_sts = new("error_internal_sts");
            this.error_internal_sts.configure(this, 1, 0, "W1C", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(error_internal_sts_bit_cg[bt]) error_internal_sts_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02

    // Reg - abr_reg::intr_block_t::notif_intr_t_notif_cmd_done_sts_1c68637e
    class abr_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e_bit_cg notif_cmd_done_sts_bit_cg[1];
        abr_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e_fld_cg fld_cg;
        rand uvm_reg_field notif_cmd_done_sts;

        function new(string name = "abr_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.notif_cmd_done_sts = new("notif_cmd_done_sts");
            this.notif_cmd_done_sts.configure(this, 1, 0, "W1C", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(notif_cmd_done_sts_bit_cg[bt]) notif_cmd_done_sts_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e

    // Reg - abr_reg::intr_block_t::error_intr_trig_t
    class abr_reg__intr_block_t__error_intr_trig_t extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__intr_block_t__error_intr_trig_t_bit_cg error_internal_trig_bit_cg[1];
        abr_reg__intr_block_t__error_intr_trig_t_fld_cg fld_cg;
        rand uvm_reg_field error_internal_trig;

        function new(string name = "abr_reg__intr_block_t__error_intr_trig_t");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.error_internal_trig = new("error_internal_trig");
            this.error_internal_trig.configure(this, 1, 0, "W1S", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(error_internal_trig_bit_cg[bt]) error_internal_trig_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__intr_block_t__error_intr_trig_t

    // Reg - abr_reg::intr_block_t::notif_intr_trig_t
    class abr_reg__intr_block_t__notif_intr_trig_t extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__intr_block_t__notif_intr_trig_t_bit_cg notif_cmd_done_trig_bit_cg[1];
        abr_reg__intr_block_t__notif_intr_trig_t_fld_cg fld_cg;
        rand uvm_reg_field notif_cmd_done_trig;

        function new(string name = "abr_reg__intr_block_t__notif_intr_trig_t");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.notif_cmd_done_trig = new("notif_cmd_done_trig");
            this.notif_cmd_done_trig.configure(this, 1, 0, "W1S", 0, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(notif_cmd_done_trig_bit_cg[bt]) notif_cmd_done_trig_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__intr_block_t__notif_intr_trig_t

    // Reg - abr_reg::intr_block_t::intr_count_t_cnt_60ddff93
    class abr_reg__intr_block_t__intr_count_t_cnt_60ddff93 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__intr_block_t__intr_count_t_cnt_60ddff93_bit_cg cnt_bit_cg[32];
        abr_reg__intr_block_t__intr_count_t_cnt_60ddff93_fld_cg fld_cg;
        rand uvm_reg_field cnt;

        function new(string name = "abr_reg__intr_block_t__intr_count_t_cnt_60ddff93");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.cnt = new("cnt");
            this.cnt.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(cnt_bit_cg[bt]) cnt_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__intr_block_t__intr_count_t_cnt_60ddff93

    // Reg - abr_reg::intr_block_t::intr_count_t_cnt_be67d6d5
    class abr_reg__intr_block_t__intr_count_t_cnt_be67d6d5 extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__intr_block_t__intr_count_t_cnt_be67d6d5_bit_cg cnt_bit_cg[32];
        abr_reg__intr_block_t__intr_count_t_cnt_be67d6d5_fld_cg fld_cg;
        rand uvm_reg_field cnt;

        function new(string name = "abr_reg__intr_block_t__intr_count_t_cnt_be67d6d5");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.cnt = new("cnt");
            this.cnt.configure(this, 32, 0, "RW", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(cnt_bit_cg[bt]) cnt_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__intr_block_t__intr_count_t_cnt_be67d6d5

    // Reg - abr_reg::intr_block_t::intr_count_incr_t_pulse_15e6ed7e
    class abr_reg__intr_block_t__intr_count_incr_t_pulse_15e6ed7e extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__intr_block_t__intr_count_incr_t_pulse_15e6ed7e_bit_cg pulse_bit_cg[1];
        abr_reg__intr_block_t__intr_count_incr_t_pulse_15e6ed7e_fld_cg fld_cg;
        rand uvm_reg_field pulse;

        function new(string name = "abr_reg__intr_block_t__intr_count_incr_t_pulse_15e6ed7e");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.pulse = new("pulse");
            this.pulse.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(pulse_bit_cg[bt]) pulse_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__intr_block_t__intr_count_incr_t_pulse_15e6ed7e

    // Reg - abr_reg::intr_block_t::intr_count_incr_t_pulse_6173128e
    class abr_reg__intr_block_t__intr_count_incr_t_pulse_6173128e extends uvm_reg;
        protected uvm_reg_data_t m_current;
        protected uvm_reg_data_t m_data;
        protected bit            m_is_read;

        abr_reg__intr_block_t__intr_count_incr_t_pulse_6173128e_bit_cg pulse_bit_cg[1];
        abr_reg__intr_block_t__intr_count_incr_t_pulse_6173128e_fld_cg fld_cg;
        rand uvm_reg_field pulse;

        function new(string name = "abr_reg__intr_block_t__intr_count_incr_t_pulse_6173128e");
            super.new(name, 32, build_coverage(UVM_CVR_ALL));
        endfunction : new
        extern virtual function void sample_values();
        extern protected virtual function void sample(uvm_reg_data_t  data,
                                                      uvm_reg_data_t  byte_en,
                                                      bit             is_read,
                                                      uvm_reg_map     map);

        virtual function void build();
            this.pulse = new("pulse");
            this.pulse.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            if (has_coverage(UVM_CVR_REG_BITS)) begin
                foreach(pulse_bit_cg[bt]) pulse_bit_cg[bt] = new();
            end
            if (has_coverage(UVM_CVR_FIELD_VALS))
                fld_cg = new();
        endfunction : build
    endclass : abr_reg__intr_block_t__intr_count_incr_t_pulse_6173128e

    // Regfile - abr_reg::intr_block_t
    class abr_reg__intr_block_t extends uvm_reg_block;
        rand abr_reg__intr_block_t__global_intr_en_t global_intr_en_r;
        rand abr_reg__intr_block_t__error_intr_en_t error_intr_en_r;
        rand abr_reg__intr_block_t__notif_intr_en_t notif_intr_en_r;
        rand abr_reg__intr_block_t__global_intr_t_agg_sts_dd3dcf0a error_global_intr_r;
        rand abr_reg__intr_block_t__global_intr_t_agg_sts_e6399b4a notif_global_intr_r;
        rand abr_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02 error_internal_intr_r;
        rand abr_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e notif_internal_intr_r;
        rand abr_reg__intr_block_t__error_intr_trig_t error_intr_trig_r;
        rand abr_reg__intr_block_t__notif_intr_trig_t notif_intr_trig_r;
        rand abr_reg__intr_block_t__intr_count_t_cnt_60ddff93 error_internal_intr_count_r;
        rand abr_reg__intr_block_t__intr_count_t_cnt_be67d6d5 notif_cmd_done_intr_count_r;
        rand abr_reg__intr_block_t__intr_count_incr_t_pulse_15e6ed7e error_internal_intr_count_incr_r;
        rand abr_reg__intr_block_t__intr_count_incr_t_pulse_6173128e notif_cmd_done_intr_count_incr_r;

        function new(string name = "abr_reg__intr_block_t");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.global_intr_en_r = new("global_intr_en_r");
            this.global_intr_en_r.configure(this);

            this.global_intr_en_r.build();
            this.default_map.add_reg(this.global_intr_en_r, 'h0);
            this.error_intr_en_r = new("error_intr_en_r");
            this.error_intr_en_r.configure(this);

            this.error_intr_en_r.build();
            this.default_map.add_reg(this.error_intr_en_r, 'h4);
            this.notif_intr_en_r = new("notif_intr_en_r");
            this.notif_intr_en_r.configure(this);

            this.notif_intr_en_r.build();
            this.default_map.add_reg(this.notif_intr_en_r, 'h8);
            this.error_global_intr_r = new("error_global_intr_r");
            this.error_global_intr_r.configure(this);

            this.error_global_intr_r.build();
            this.default_map.add_reg(this.error_global_intr_r, 'hc);
            this.notif_global_intr_r = new("notif_global_intr_r");
            this.notif_global_intr_r.configure(this);

            this.notif_global_intr_r.build();
            this.default_map.add_reg(this.notif_global_intr_r, 'h10);
            this.error_internal_intr_r = new("error_internal_intr_r");
            this.error_internal_intr_r.configure(this);

            this.error_internal_intr_r.build();
            this.default_map.add_reg(this.error_internal_intr_r, 'h14);
            this.notif_internal_intr_r = new("notif_internal_intr_r");
            this.notif_internal_intr_r.configure(this);

            this.notif_internal_intr_r.build();
            this.default_map.add_reg(this.notif_internal_intr_r, 'h18);
            this.error_intr_trig_r = new("error_intr_trig_r");
            this.error_intr_trig_r.configure(this);

            this.error_intr_trig_r.build();
            this.default_map.add_reg(this.error_intr_trig_r, 'h1c);
            this.notif_intr_trig_r = new("notif_intr_trig_r");
            this.notif_intr_trig_r.configure(this);

            this.notif_intr_trig_r.build();
            this.default_map.add_reg(this.notif_intr_trig_r, 'h20);
            this.error_internal_intr_count_r = new("error_internal_intr_count_r");
            this.error_internal_intr_count_r.configure(this);

            this.error_internal_intr_count_r.build();
            this.default_map.add_reg(this.error_internal_intr_count_r, 'h100);
            this.notif_cmd_done_intr_count_r = new("notif_cmd_done_intr_count_r");
            this.notif_cmd_done_intr_count_r.configure(this);

            this.notif_cmd_done_intr_count_r.build();
            this.default_map.add_reg(this.notif_cmd_done_intr_count_r, 'h180);
            this.error_internal_intr_count_incr_r = new("error_internal_intr_count_incr_r");
            this.error_internal_intr_count_incr_r.configure(this);

            this.error_internal_intr_count_incr_r.build();
            this.default_map.add_reg(this.error_internal_intr_count_incr_r, 'h200);
            this.notif_cmd_done_intr_count_incr_r = new("notif_cmd_done_intr_count_incr_r");
            this.notif_cmd_done_intr_count_incr_r.configure(this);

            this.notif_cmd_done_intr_count_incr_r.build();
            this.default_map.add_reg(this.notif_cmd_done_intr_count_incr_r, 'h204);
        endfunction : build
    endclass : abr_reg__intr_block_t

    // Addrmap - abr_reg
    class abr_reg extends uvm_reg_block;
        rand abr_reg__MLDSA_NAME MLDSA_NAME[2];
        rand abr_reg__MLDSA_VERSION MLDSA_VERSION[2];
        rand abr_reg__MLDSA_CTRL MLDSA_CTRL;
        rand abr_reg__MLDSA_STATUS MLDSA_STATUS;
        rand abr_reg__ABR_ENTROPY ABR_ENTROPY[16];
        rand abr_reg__MLDSA_SEED MLDSA_SEED[8];
        rand abr_reg__MLDSA_SIGN_RND MLDSA_SIGN_RND[8];
        rand abr_reg__MLDSA_MSG MLDSA_MSG[16];
        rand abr_reg__MLDSA_VERIFY_RES MLDSA_VERIFY_RES[16];
        rand abr_reg__MLDSA_EXTERNAL_MU MLDSA_EXTERNAL_MU[16];
        rand abr_reg__MLDSA_MSG_STROBE MLDSA_MSG_STROBE;
        rand abr_reg__MLDSA_CTX_CONFIG MLDSA_CTX_CONFIG;
        rand abr_reg__MLDSA_CTX MLDSA_CTX[64];
        rand abr_reg__MLDSA_PUBKEY MLDSA_PUBKEY;
        rand abr_reg__MLDSA_SIGNATURE MLDSA_SIGNATURE;
        rand abr_reg__MLDSA_PRIVKEY_OUT MLDSA_PRIVKEY_OUT;
        rand abr_reg__MLDSA_PRIVKEY_IN MLDSA_PRIVKEY_IN;
        rand kv_read_ctrl_reg kv_mldsa_seed_rd_ctrl;
        rand kv_status_reg kv_mldsa_seed_rd_status;
        rand abr_reg__MLKEM_NAME MLKEM_NAME[2];
        rand abr_reg__MLKEM_VERSION MLKEM_VERSION[2];
        rand abr_reg__MLKEM_CTRL MLKEM_CTRL;
        rand abr_reg__MLKEM_STATUS MLKEM_STATUS;
        rand abr_reg__MLKEM_SEED_D MLKEM_SEED_D[8];
        rand abr_reg__MLKEM_SEED_Z MLKEM_SEED_Z[8];
        rand abr_reg__MLKEM_SHARED_KEY MLKEM_SHARED_KEY[8];
        rand abr_reg__MLKEM_MSG MLKEM_MSG;
        rand abr_reg__MLKEM_DECAPS_KEY MLKEM_DECAPS_KEY;
        rand abr_reg__MLKEM_ENCAPS_KEY MLKEM_ENCAPS_KEY;
        rand abr_reg__MLKEM_CIPHERTEXT MLKEM_CIPHERTEXT;
        rand kv_read_ctrl_reg kv_mlkem_seed_rd_ctrl;
        rand kv_status_reg kv_mlkem_seed_rd_status;
        rand kv_read_ctrl_reg kv_mlkem_msg_rd_ctrl;
        rand kv_status_reg kv_mlkem_msg_rd_status;
        rand kv_write_ctrl_reg kv_mlkem_sharedkey_wr_ctrl;
        rand kv_status_reg kv_mlkem_sharedkey_wr_status;
        rand abr_reg__intr_block_t intr_block_rf;

        function new(string name = "abr_reg");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            foreach(this.MLDSA_NAME[i0]) begin
                this.MLDSA_NAME[i0] = new($sformatf("MLDSA_NAME[%0d]", i0));
                this.MLDSA_NAME[i0].configure(this);
                
                this.MLDSA_NAME[i0].build();
                this.default_map.add_reg(this.MLDSA_NAME[i0], 'h0 + i0*'h4);
            end
            foreach(this.MLDSA_VERSION[i0]) begin
                this.MLDSA_VERSION[i0] = new($sformatf("MLDSA_VERSION[%0d]", i0));
                this.MLDSA_VERSION[i0].configure(this);
                
                this.MLDSA_VERSION[i0].build();
                this.default_map.add_reg(this.MLDSA_VERSION[i0], 'h8 + i0*'h4);
            end
            this.MLDSA_CTRL = new("MLDSA_CTRL");
            this.MLDSA_CTRL.configure(this);

            this.MLDSA_CTRL.build();
            this.default_map.add_reg(this.MLDSA_CTRL, 'h10);
            this.MLDSA_STATUS = new("MLDSA_STATUS");
            this.MLDSA_STATUS.configure(this);

            this.MLDSA_STATUS.build();
            this.default_map.add_reg(this.MLDSA_STATUS, 'h14);
            foreach(this.ABR_ENTROPY[i0]) begin
                this.ABR_ENTROPY[i0] = new($sformatf("ABR_ENTROPY[%0d]", i0));
                this.ABR_ENTROPY[i0].configure(this);
                
                this.ABR_ENTROPY[i0].build();
                this.default_map.add_reg(this.ABR_ENTROPY[i0], 'h18 + i0*'h4);
            end
            foreach(this.MLDSA_SEED[i0]) begin
                this.MLDSA_SEED[i0] = new($sformatf("MLDSA_SEED[%0d]", i0));
                this.MLDSA_SEED[i0].configure(this);
                
                this.MLDSA_SEED[i0].build();
                this.default_map.add_reg(this.MLDSA_SEED[i0], 'h58 + i0*'h4);
            end
            foreach(this.MLDSA_SIGN_RND[i0]) begin
                this.MLDSA_SIGN_RND[i0] = new($sformatf("MLDSA_SIGN_RND[%0d]", i0));
                this.MLDSA_SIGN_RND[i0].configure(this);
                
                this.MLDSA_SIGN_RND[i0].build();
                this.default_map.add_reg(this.MLDSA_SIGN_RND[i0], 'h78 + i0*'h4);
            end
            foreach(this.MLDSA_MSG[i0]) begin
                this.MLDSA_MSG[i0] = new($sformatf("MLDSA_MSG[%0d]", i0));
                this.MLDSA_MSG[i0].configure(this);
                
                this.MLDSA_MSG[i0].build();
                this.default_map.add_reg(this.MLDSA_MSG[i0], 'h98 + i0*'h4);
            end
            foreach(this.MLDSA_VERIFY_RES[i0]) begin
                this.MLDSA_VERIFY_RES[i0] = new($sformatf("MLDSA_VERIFY_RES[%0d]", i0));
                this.MLDSA_VERIFY_RES[i0].configure(this);
                
                this.MLDSA_VERIFY_RES[i0].build();
                this.default_map.add_reg(this.MLDSA_VERIFY_RES[i0], 'hd8 + i0*'h4);
            end
            foreach(this.MLDSA_EXTERNAL_MU[i0]) begin
                this.MLDSA_EXTERNAL_MU[i0] = new($sformatf("MLDSA_EXTERNAL_MU[%0d]", i0));
                this.MLDSA_EXTERNAL_MU[i0].configure(this);
                
                this.MLDSA_EXTERNAL_MU[i0].build();
                this.default_map.add_reg(this.MLDSA_EXTERNAL_MU[i0], 'h118 + i0*'h4);
            end
            this.MLDSA_MSG_STROBE = new("MLDSA_MSG_STROBE");
            this.MLDSA_MSG_STROBE.configure(this);

            this.MLDSA_MSG_STROBE.build();
            this.default_map.add_reg(this.MLDSA_MSG_STROBE, 'h158);
            this.MLDSA_CTX_CONFIG = new("MLDSA_CTX_CONFIG");
            this.MLDSA_CTX_CONFIG.configure(this);

            this.MLDSA_CTX_CONFIG.build();
            this.default_map.add_reg(this.MLDSA_CTX_CONFIG, 'h15c);
            foreach(this.MLDSA_CTX[i0]) begin
                this.MLDSA_CTX[i0] = new($sformatf("MLDSA_CTX[%0d]", i0));
                this.MLDSA_CTX[i0].configure(this);
                
                this.MLDSA_CTX[i0].build();
                this.default_map.add_reg(this.MLDSA_CTX[i0], 'h160 + i0*'h4);
            end
            this.MLDSA_PUBKEY = new("MLDSA_PUBKEY");
            this.MLDSA_PUBKEY.configure(this);
            this.MLDSA_PUBKEY.build();
            this.default_map.add_submap(this.MLDSA_PUBKEY.default_map, 'h1000);
            this.MLDSA_SIGNATURE = new("MLDSA_SIGNATURE");
            this.MLDSA_SIGNATURE.configure(this);
            this.MLDSA_SIGNATURE.build();
            this.default_map.add_submap(this.MLDSA_SIGNATURE.default_map, 'h2000);
            this.MLDSA_PRIVKEY_OUT = new("MLDSA_PRIVKEY_OUT");
            this.MLDSA_PRIVKEY_OUT.configure(this);
            this.MLDSA_PRIVKEY_OUT.build();
            this.default_map.add_submap(this.MLDSA_PRIVKEY_OUT.default_map, 'h4000);
            this.MLDSA_PRIVKEY_IN = new("MLDSA_PRIVKEY_IN");
            this.MLDSA_PRIVKEY_IN.configure(this);
            this.MLDSA_PRIVKEY_IN.build();
            this.default_map.add_submap(this.MLDSA_PRIVKEY_IN.default_map, 'h6000);
            this.kv_mldsa_seed_rd_ctrl = new("kv_mldsa_seed_rd_ctrl");
            this.kv_mldsa_seed_rd_ctrl.configure(this);

            this.kv_mldsa_seed_rd_ctrl.build();
            this.default_map.add_reg(this.kv_mldsa_seed_rd_ctrl, 'h7320);
            this.kv_mldsa_seed_rd_status = new("kv_mldsa_seed_rd_status");
            this.kv_mldsa_seed_rd_status.configure(this);

            this.kv_mldsa_seed_rd_status.build();
            this.default_map.add_reg(this.kv_mldsa_seed_rd_status, 'h7324);
            foreach(this.MLKEM_NAME[i0]) begin
                this.MLKEM_NAME[i0] = new($sformatf("MLKEM_NAME[%0d]", i0));
                this.MLKEM_NAME[i0].configure(this);
                
                this.MLKEM_NAME[i0].build();
                this.default_map.add_reg(this.MLKEM_NAME[i0], 'h8000 + i0*'h4);
            end
            foreach(this.MLKEM_VERSION[i0]) begin
                this.MLKEM_VERSION[i0] = new($sformatf("MLKEM_VERSION[%0d]", i0));
                this.MLKEM_VERSION[i0].configure(this);
                
                this.MLKEM_VERSION[i0].build();
                this.default_map.add_reg(this.MLKEM_VERSION[i0], 'h8008 + i0*'h4);
            end
            this.MLKEM_CTRL = new("MLKEM_CTRL");
            this.MLKEM_CTRL.configure(this);

            this.MLKEM_CTRL.build();
            this.default_map.add_reg(this.MLKEM_CTRL, 'h8010);
            this.MLKEM_STATUS = new("MLKEM_STATUS");
            this.MLKEM_STATUS.configure(this);

            this.MLKEM_STATUS.build();
            this.default_map.add_reg(this.MLKEM_STATUS, 'h8014);
            foreach(this.MLKEM_SEED_D[i0]) begin
                this.MLKEM_SEED_D[i0] = new($sformatf("MLKEM_SEED_D[%0d]", i0));
                this.MLKEM_SEED_D[i0].configure(this);
                
                this.MLKEM_SEED_D[i0].build();
                this.default_map.add_reg(this.MLKEM_SEED_D[i0], 'h8018 + i0*'h4);
            end
            foreach(this.MLKEM_SEED_Z[i0]) begin
                this.MLKEM_SEED_Z[i0] = new($sformatf("MLKEM_SEED_Z[%0d]", i0));
                this.MLKEM_SEED_Z[i0].configure(this);
                
                this.MLKEM_SEED_Z[i0].build();
                this.default_map.add_reg(this.MLKEM_SEED_Z[i0], 'h8038 + i0*'h4);
            end
            foreach(this.MLKEM_SHARED_KEY[i0]) begin
                this.MLKEM_SHARED_KEY[i0] = new($sformatf("MLKEM_SHARED_KEY[%0d]", i0));
                this.MLKEM_SHARED_KEY[i0].configure(this);
                
                this.MLKEM_SHARED_KEY[i0].build();
                this.default_map.add_reg(this.MLKEM_SHARED_KEY[i0], 'h8058 + i0*'h4);
            end
            this.MLKEM_MSG = new("MLKEM_MSG");
            this.MLKEM_MSG.configure(this);
            this.MLKEM_MSG.build();
            this.default_map.add_submap(this.MLKEM_MSG.default_map, 'h8080);
            this.MLKEM_DECAPS_KEY = new("MLKEM_DECAPS_KEY");
            this.MLKEM_DECAPS_KEY.configure(this);
            this.MLKEM_DECAPS_KEY.build();
            this.default_map.add_submap(this.MLKEM_DECAPS_KEY.default_map, 'h9000);
            this.MLKEM_ENCAPS_KEY = new("MLKEM_ENCAPS_KEY");
            this.MLKEM_ENCAPS_KEY.configure(this);
            this.MLKEM_ENCAPS_KEY.build();
            this.default_map.add_submap(this.MLKEM_ENCAPS_KEY.default_map, 'ha000);
            this.MLKEM_CIPHERTEXT = new("MLKEM_CIPHERTEXT");
            this.MLKEM_CIPHERTEXT.configure(this);
            this.MLKEM_CIPHERTEXT.build();
            this.default_map.add_submap(this.MLKEM_CIPHERTEXT.default_map, 'ha800);
            this.kv_mlkem_seed_rd_ctrl = new("kv_mlkem_seed_rd_ctrl");
            this.kv_mlkem_seed_rd_ctrl.configure(this);

            this.kv_mlkem_seed_rd_ctrl.build();
            this.default_map.add_reg(this.kv_mlkem_seed_rd_ctrl, 'hae20);
            this.kv_mlkem_seed_rd_status = new("kv_mlkem_seed_rd_status");
            this.kv_mlkem_seed_rd_status.configure(this);

            this.kv_mlkem_seed_rd_status.build();
            this.default_map.add_reg(this.kv_mlkem_seed_rd_status, 'hae24);
            this.kv_mlkem_msg_rd_ctrl = new("kv_mlkem_msg_rd_ctrl");
            this.kv_mlkem_msg_rd_ctrl.configure(this);

            this.kv_mlkem_msg_rd_ctrl.build();
            this.default_map.add_reg(this.kv_mlkem_msg_rd_ctrl, 'hae28);
            this.kv_mlkem_msg_rd_status = new("kv_mlkem_msg_rd_status");
            this.kv_mlkem_msg_rd_status.configure(this);

            this.kv_mlkem_msg_rd_status.build();
            this.default_map.add_reg(this.kv_mlkem_msg_rd_status, 'hae2c);
            this.kv_mlkem_sharedkey_wr_ctrl = new("kv_mlkem_sharedkey_wr_ctrl");
            this.kv_mlkem_sharedkey_wr_ctrl.configure(this);

            this.kv_mlkem_sharedkey_wr_ctrl.build();
            this.default_map.add_reg(this.kv_mlkem_sharedkey_wr_ctrl, 'hae30);
            this.kv_mlkem_sharedkey_wr_status = new("kv_mlkem_sharedkey_wr_status");
            this.kv_mlkem_sharedkey_wr_status.configure(this);

            this.kv_mlkem_sharedkey_wr_status.build();
            this.default_map.add_reg(this.kv_mlkem_sharedkey_wr_status, 'hae34);
            this.intr_block_rf = new("intr_block_rf");
            this.intr_block_rf.configure(this);
            this.intr_block_rf.build();
            this.default_map.add_submap(this.intr_block_rf.default_map, 'hb000);
        endfunction : build
    endclass : abr_reg

    `include "abr_reg_sample.svh"
endpackage: abr_reg_uvm
