// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package adamsbridge_reg_pkg;

    localparam ADAMSBRIDGE_REG_DATA_WIDTH = 32;
    localparam ADAMSBRIDGE_REG_MIN_ADDR_WIDTH = 15;

    typedef struct packed{
        logic [31:0] next;
    } adamsbridge_reg__ADAMSBRIDGE_NAME__NAME__in_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_NAME__NAME__in_t NAME;
    } adamsbridge_reg__ADAMSBRIDGE_NAME__in_t;

    typedef struct packed{
        logic [31:0] next;
    } adamsbridge_reg__ADAMSBRIDGE_VERSION__VERSION__in_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_VERSION__VERSION__in_t VERSION;
    } adamsbridge_reg__ADAMSBRIDGE_VERSION__in_t;

    typedef struct packed{
        logic hwclr;
    } adamsbridge_reg__ADAMSBRIDGE_CTRL__CTRL__in_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_CTRL__CTRL__in_t CTRL;
    } adamsbridge_reg__ADAMSBRIDGE_CTRL__in_t;

    typedef struct packed{
        logic next;
    } adamsbridge_reg__ADAMSBRIDGE_STATUS__READY__in_t;

    typedef struct packed{
        logic next;
    } adamsbridge_reg__ADAMSBRIDGE_STATUS__VALID__in_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_STATUS__READY__in_t READY;
        adamsbridge_reg__ADAMSBRIDGE_STATUS__VALID__in_t VALID;
    } adamsbridge_reg__ADAMSBRIDGE_STATUS__in_t;

    typedef struct packed{
        logic hwclr;
    } adamsbridge_reg__ADAMSBRIDGE_IV__IV__in_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_IV__IV__in_t IV;
    } adamsbridge_reg__ADAMSBRIDGE_IV__in_t;

    typedef struct packed{
        logic [31:0] next;
        logic we;
        logic hwclr;
    } adamsbridge_reg__ADAMSBRIDGE_SEED__SEED__in_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_SEED__SEED__in_t SEED;
    } adamsbridge_reg__ADAMSBRIDGE_SEED__in_t;

    typedef struct packed{
        logic hwclr;
    } adamsbridge_reg__ADAMSBRIDGE_SIGN_RND__SIGN_RND__in_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_SIGN_RND__SIGN_RND__in_t SIGN_RND;
    } adamsbridge_reg__ADAMSBRIDGE_SIGN_RND__in_t;

    typedef struct packed{
        logic [31:0] next;
        logic we;
        logic hwclr;
    } adamsbridge_reg__ADAMSBRIDGE_MSG__MSG__in_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_MSG__MSG__in_t MSG;
    } adamsbridge_reg__ADAMSBRIDGE_MSG__in_t;

    typedef struct packed{
        logic [31:0] next;
        logic we;
        logic hwclr;
    } adamsbridge_reg__ADAMSBRIDGE_VERIFY_RES__VERIFY_RES__in_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_VERIFY_RES__VERIFY_RES__in_t VERIFY_RES;
    } adamsbridge_reg__ADAMSBRIDGE_VERIFY_RES__in_t;

    typedef struct packed{
        logic [31:0] next;
        logic we;
        logic hwclr;
    } adamsbridge_reg__ADAMSBRIDGE_PUBKEY__PUBKEY__in_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_PUBKEY__PUBKEY__in_t PUBKEY;
    } adamsbridge_reg__ADAMSBRIDGE_PUBKEY__in_t;

    typedef struct packed{
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } adamsbridge_reg__ADAMSBRIDGE_SIGNATURE__external__in_t;

    typedef struct packed{
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } adamsbridge_reg__ADAMSBRIDGE_PRIVKEY_OUT__external__in_t;

    typedef struct packed{
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } adamsbridge_reg__ADAMSBRIDGE_PRIVKEY_IN__external__in_t;

    typedef struct packed{
        logic hwset;
    } adamsbridge_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__error_internal_sts_enable_d33001bb_next_52b75ffa_resetsignal_0d7eaa27__in_t;

    typedef struct packed{
        adamsbridge_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__error_internal_sts_enable_d33001bb_next_52b75ffa_resetsignal_0d7eaa27__in_t error_internal_sts;
    } adamsbridge_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__in_t;

    typedef struct packed{
        logic hwset;
    } adamsbridge_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__notif_cmd_done_sts_enable_dabe0b8b_next_540fa3b7__in_t;

    typedef struct packed{
        adamsbridge_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__notif_cmd_done_sts_enable_dabe0b8b_next_540fa3b7__in_t notif_cmd_done_sts;
    } adamsbridge_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__in_t;

    typedef struct packed{
        adamsbridge_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__in_t error_internal_intr_r;
        adamsbridge_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__in_t notif_internal_intr_r;
    } adamsbridge_reg__intr_block_t__in_t;

    typedef struct packed{
        logic reset_b;
        logic hard_reset_b;
        logic adamsbridge_ready;
        adamsbridge_reg__ADAMSBRIDGE_NAME__in_t [2-1:0]ADAMSBRIDGE_NAME;
        adamsbridge_reg__ADAMSBRIDGE_VERSION__in_t [2-1:0]ADAMSBRIDGE_VERSION;
        adamsbridge_reg__ADAMSBRIDGE_CTRL__in_t ADAMSBRIDGE_CTRL;
        adamsbridge_reg__ADAMSBRIDGE_STATUS__in_t ADAMSBRIDGE_STATUS;
        adamsbridge_reg__ADAMSBRIDGE_IV__in_t [16-1:0]ADAMSBRIDGE_IV;
        adamsbridge_reg__ADAMSBRIDGE_SEED__in_t [8-1:0]ADAMSBRIDGE_SEED;
        adamsbridge_reg__ADAMSBRIDGE_SIGN_RND__in_t [8-1:0]ADAMSBRIDGE_SIGN_RND;
        adamsbridge_reg__ADAMSBRIDGE_MSG__in_t [16-1:0]ADAMSBRIDGE_MSG;
        adamsbridge_reg__ADAMSBRIDGE_VERIFY_RES__in_t [16-1:0]ADAMSBRIDGE_VERIFY_RES;
        adamsbridge_reg__ADAMSBRIDGE_PUBKEY__in_t [648-1:0]ADAMSBRIDGE_PUBKEY;
        adamsbridge_reg__ADAMSBRIDGE_SIGNATURE__external__in_t [1157-1:0]ADAMSBRIDGE_SIGNATURE;
        adamsbridge_reg__ADAMSBRIDGE_PRIVKEY_OUT__external__in_t ADAMSBRIDGE_PRIVKEY_OUT;
        adamsbridge_reg__ADAMSBRIDGE_PRIVKEY_IN__external__in_t ADAMSBRIDGE_PRIVKEY_IN;
        adamsbridge_reg__intr_block_t__in_t intr_block_rf;
    } adamsbridge_reg__in_t;

    typedef struct packed{
        logic [2:0] value;
    } adamsbridge_reg__ADAMSBRIDGE_CTRL__CTRL__out_t;

    typedef struct packed{
        logic value;
    } adamsbridge_reg__ADAMSBRIDGE_CTRL__ZEROIZE__out_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_CTRL__CTRL__out_t CTRL;
        adamsbridge_reg__ADAMSBRIDGE_CTRL__ZEROIZE__out_t ZEROIZE;
    } adamsbridge_reg__ADAMSBRIDGE_CTRL__out_t;

    typedef struct packed{
        logic [31:0] value;
    } adamsbridge_reg__ADAMSBRIDGE_IV__IV__out_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_IV__IV__out_t IV;
    } adamsbridge_reg__ADAMSBRIDGE_IV__out_t;

    typedef struct packed{
        logic [31:0] value;
    } adamsbridge_reg__ADAMSBRIDGE_SEED__SEED__out_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_SEED__SEED__out_t SEED;
    } adamsbridge_reg__ADAMSBRIDGE_SEED__out_t;

    typedef struct packed{
        logic [31:0] value;
    } adamsbridge_reg__ADAMSBRIDGE_SIGN_RND__SIGN_RND__out_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_SIGN_RND__SIGN_RND__out_t SIGN_RND;
    } adamsbridge_reg__ADAMSBRIDGE_SIGN_RND__out_t;

    typedef struct packed{
        logic [31:0] value;
    } adamsbridge_reg__ADAMSBRIDGE_MSG__MSG__out_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_MSG__MSG__out_t MSG;
    } adamsbridge_reg__ADAMSBRIDGE_MSG__out_t;

    typedef struct packed{
        logic [31:0] value;
    } adamsbridge_reg__ADAMSBRIDGE_VERIFY_RES__VERIFY_RES__out_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_VERIFY_RES__VERIFY_RES__out_t VERIFY_RES;
    } adamsbridge_reg__ADAMSBRIDGE_VERIFY_RES__out_t;

    typedef struct packed{
        logic [31:0] value;
    } adamsbridge_reg__ADAMSBRIDGE_PUBKEY__PUBKEY__out_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_PUBKEY__PUBKEY__out_t PUBKEY;
    } adamsbridge_reg__ADAMSBRIDGE_PUBKEY__out_t;

    typedef struct packed{
        logic req;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } adamsbridge_reg__ADAMSBRIDGE_SIGNATURE__external__out_t;

    typedef struct packed{
        logic req;
        logic [12:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } adamsbridge_reg__ADAMSBRIDGE_PRIVKEY_OUT__external__out_t;

    typedef struct packed{
        logic req;
        logic [12:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } adamsbridge_reg__ADAMSBRIDGE_PRIVKEY_IN__external__out_t;

    typedef struct packed{
        logic intr;
    } adamsbridge_reg__intr_block_t__global_intr_t_agg_sts_dd3dcf0a__out_t;

    typedef struct packed{
        logic intr;
    } adamsbridge_reg__intr_block_t__global_intr_t_agg_sts_e6399b4a__out_t;

    typedef struct packed{
        logic intr;
    } adamsbridge_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__out_t;

    typedef struct packed{
        logic intr;
    } adamsbridge_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__out_t;

    typedef struct packed{
        adamsbridge_reg__intr_block_t__global_intr_t_agg_sts_dd3dcf0a__out_t error_global_intr_r;
        adamsbridge_reg__intr_block_t__global_intr_t_agg_sts_e6399b4a__out_t notif_global_intr_r;
        adamsbridge_reg__intr_block_t__error_intr_t_error_internal_sts_83adab02__out_t error_internal_intr_r;
        adamsbridge_reg__intr_block_t__notif_intr_t_notif_cmd_done_sts_1c68637e__out_t notif_internal_intr_r;
    } adamsbridge_reg__intr_block_t__out_t;

    typedef struct packed{
        adamsbridge_reg__ADAMSBRIDGE_CTRL__out_t ADAMSBRIDGE_CTRL;
        adamsbridge_reg__ADAMSBRIDGE_IV__out_t [16-1:0]ADAMSBRIDGE_IV;
        adamsbridge_reg__ADAMSBRIDGE_SEED__out_t [8-1:0]ADAMSBRIDGE_SEED;
        adamsbridge_reg__ADAMSBRIDGE_SIGN_RND__out_t [8-1:0]ADAMSBRIDGE_SIGN_RND;
        adamsbridge_reg__ADAMSBRIDGE_MSG__out_t [16-1:0]ADAMSBRIDGE_MSG;
        adamsbridge_reg__ADAMSBRIDGE_VERIFY_RES__out_t [16-1:0]ADAMSBRIDGE_VERIFY_RES;
        adamsbridge_reg__ADAMSBRIDGE_PUBKEY__out_t [648-1:0]ADAMSBRIDGE_PUBKEY;
        adamsbridge_reg__ADAMSBRIDGE_SIGNATURE__external__out_t [1157-1:0]ADAMSBRIDGE_SIGNATURE;
        adamsbridge_reg__ADAMSBRIDGE_PRIVKEY_OUT__external__out_t ADAMSBRIDGE_PRIVKEY_OUT;
        adamsbridge_reg__ADAMSBRIDGE_PRIVKEY_IN__external__out_t ADAMSBRIDGE_PRIVKEY_IN;
        adamsbridge_reg__intr_block_t__out_t intr_block_rf;
    } adamsbridge_reg__out_t;

    localparam ADAMSBRIDGE_REG_ADDR_WIDTH = 32'd15;

endpackage