---
provides: [abr_defines]
schema_version: 2.4.0
targets:
  tb:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/config_defines.svh
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/config_defines.svh
---
provides: [adamsbridge_top]
schema_version: 2.4.0
requires:
  - abr_defines
  - abr_libs
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/adamsbridge_top.sv
    tops: [adamsbridge_top]
  rtl_lint:
    waiver_files: []
    options: []
global:
  tool:
    vcs:
      default:
        - '-assert svaext'