---
provides: [abr_sampler_pkg]
schema_version: 2.4.0
requires:
  - mldsa_defines
targets:
  tb:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/abr_sampler_pkg.sv
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/abr_sampler_pkg.sv
---
provides: [abr_sampler_top]
schema_version: 2.4.0
requires:
  - abr_sampler_pkg
  - mldsa_defines
  - abr_libs
  - rej_bounded
  - rej_sampler
  - exp_mask
  - sample_in_ball
  - abr_sha3
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/abr_sampler_top.sv
    tops: [abr_sampler_top]
