---
provides: [abr_prim_pkg]
schema_version: 2.4.0
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/abr_prim_util_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_alert_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_subreg_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_mubi_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_cipher_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_sparse_fsm_pkg.sv
  tb:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/abr_prim_util_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_alert_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_subreg_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_mubi_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_cipher_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_sparse_fsm_pkg.sv
---
provides: [abr_prim]
schema_version: 2.4.0
requires:
  - abr_prim_pkg
  - abr_prim_generic
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/abr_prim_flop_en.sv
      - $COMPILE_ROOT/rtl/abr_prim_cdc_rand_delay.sv
      - $COMPILE_ROOT/rtl/abr_prim_flop_2sync.sv
      - $COMPILE_ROOT/rtl/abr_prim_lfsr.sv
      - $COMPILE_ROOT/rtl/abr_prim_mubi4_sync.sv
      - $COMPILE_ROOT/rtl/abr_prim_diff_decode.sv
      - $COMPILE_ROOT/rtl/abr_prim_sec_anchor_buf.sv
      - $COMPILE_ROOT/rtl/abr_prim_slicer.sv
      - $COMPILE_ROOT/rtl/abr_prim_count.sv
      - $COMPILE_ROOT/rtl/abr_prim_sparse_fsm_flop.sv
      - $COMPILE_ROOT/rtl/abr_prim_dom_and_2share.sv
      - $COMPILE_ROOT/rtl/abr_prim_sec_anchor_flop.sv
      - $COMPILE_ROOT/rtl/abr_prim_reg_we_check.sv
      - $COMPILE_ROOT/rtl/abr_prim_packer_fifo.sv
      - $COMPILE_ROOT/rtl/abr_prim_max_tree.sv
      - $COMPILE_ROOT/rtl/abr_prim_subreg_arb.sv
      - $COMPILE_ROOT/rtl/abr_prim_subreg.sv
      - $COMPILE_ROOT/rtl/abr_prim_intr_hw.sv
      - $COMPILE_ROOT/rtl/abr_prim_onehot_check.sv
      - $COMPILE_ROOT/rtl/abr_prim_mubi8_sync.sv
      - $COMPILE_ROOT/rtl/abr_prim_fifo_sync_cnt.sv
      - $COMPILE_ROOT/rtl/abr_prim_buf.sv
      #- $COMPILE_ROOT/rtl/abr_prim_lc_sync.sv
      - $COMPILE_ROOT/rtl/abr_prim_alert_receiver.sv
      - $COMPILE_ROOT/rtl/abr_prim_flop.sv
      - $COMPILE_ROOT/rtl/abr_prim_alert_sender.sv
      - $COMPILE_ROOT/rtl/abr_prim_fifo_sync.sv
      - $COMPILE_ROOT/rtl/abr_prim_arbiter_ppc.sv
      - $COMPILE_ROOT/rtl/abr_prim_sum_tree.sv
      - $COMPILE_ROOT/rtl/abr_prim_subreg_ext.sv
      - $COMPILE_ROOT/rtl/abr_prim_edge_detector.sv
    tops: [abr_prim]
