---
provides: [abr_prim_pkg]
schema_version: 2.4.0
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/abr_prim_alert_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_mubi_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_cipher_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_sparse_fsm_pkg.sv
  tb:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/abr_prim_alert_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_mubi_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_cipher_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_pkg.sv
      - $COMPILE_ROOT/rtl/abr_prim_sparse_fsm_pkg.sv
---
provides: [abr_prim]
schema_version: 2.4.0
requires:
  - abr_prim_pkg
  - abr_prim_generic
targets:
  rtl:
    directories: [$COMPILE_ROOT/rtl]
    files:
      - $COMPILE_ROOT/rtl/abr_prim_lfsr.sv
      - $COMPILE_ROOT/rtl/abr_prim_sec_anchor_buf.sv
      - $COMPILE_ROOT/rtl/abr_prim_count.sv
      - $COMPILE_ROOT/rtl/abr_prim_sparse_fsm_flop.sv
      - $COMPILE_ROOT/rtl/abr_prim_dom_and_2share.sv
      - $COMPILE_ROOT/rtl/abr_prim_buf.sv
      - $COMPILE_ROOT/rtl/abr_prim_flop.sv
    tops: [abr_prim]
